FROM ubuntu:disco

RUN dpkg --add-architecture i386 && \
    apt-get update && \
    apt-get install -y cmake build-essential g++ gcc g++-multilib gcc-multilib \
                        libsdl2-dev libopenal-dev libsdl2-2.0-0:i386 libopenal1:i386 libgl1:i386 \
                        python2.7 git

RUN ln -s `which python2.7` /bin/python

RUN git clone https://github.com/emscripten-core/emsdk.git /emsdk

WORKDIR /emsdk

RUN ./emsdk install latest && ./emsdk activate latest && ./emsdk_env.sh
ENV EMPATH /emsdk/upstream/emscripten

WORKDIR /src
COPY ./src .

RUN $EMPATH/emconfigure cmake . && $EMPATH/emmake make