FROM ubuntu:disco

RUN dpkg --add-architecture i386 && \
    apt-get update && \
    apt-get install -y cmake build-essential g++ gcc g++-multilib gcc-multilib \
                        libsdl2-dev libopenal-dev libsdl2-2.0-0:i386 libopenal1:i386 libgl1:i386

RUN cd /usr/lib/i386-linux-gnu/ && \
    ln -s libSDL2-2.0.so.0 libSDL2.so && \
    ln -s libopenal.so.1 libopenal.so && \
    ln -s libGL.so.1 libGL.so

WORKDIR /src
COPY ./src .

RUN cmake . && make