#ifndef NOX_PORT_CLIENT_DRAWABLE_UPDATE_MTAILUP
#define NOX_PORT_CLIENT_DRAWABLE_UPDATE_MTAILUP

#include "../../../defs.h"

void __cdecl sub_4CDD80(int a1, _DWORD* a2);

#endif // NOX_PORT_CLIENT_DRAWABLE_UPDATE_MTAILUP
