#ifndef NOX_PORT_CLIENT_DRAWABLE_UPDATE_TELWAKE
#define NOX_PORT_CLIENT_DRAWABLE_UPDATE_TELWAKE

#include "../../../defs.h"

int __cdecl sub_4CD8D0(int a1, int a2);

#endif // NOX_PORT_CLIENT_DRAWABLE_UPDATE_TELWAKE
