FROM nox:base_build_image AS base_build_image

RUN mkdir -p /home/runner/emsdk && \
    mkdir -p /home/runner/.emscripten_cache && \
    chown runner:runner -R /home/runner/emsdk /home/runner/.emscripten_cache

RUN apt-get update && \
    apt-get install -y \
                        python2.7 git && \
    rm -rf /var/lib/apt/lists/*

RUN ln -s $( which python2.7 ) /bin/python

RUN git clone https://github.com/emscripten-core/emsdk.git /home/runner/emsdk

WORKDIR /home/runner/emsdk

USER runner

RUN export EMSDK_VER="2.0.9" && \
    ./emsdk install $EMSDK_VER && \
    ./emsdk activate $EMSDK_VER

ENV PATH="/home/runner/emsdk/upstream/emscripten:${PATH}"

COPY --chown=runner ./start_wasm.sh /home/runner/

ENTRYPOINT ["/home/runner/start_wasm.sh"]
