FROM ubuntu:disco

ENV LANG C.UTF-8

RUN useradd --home-dir /home/runner --no-create-home --shell /bin/sh runner

RUN mkdir -p /home/runner/src && \
    mkdir -p /home/runner/bin && \
    mkdir -p /home/runner/build && \
    mkdir -p /home/runner/.ccache && \
    chown runner:runner -R /home/runner

RUN dpkg --add-architecture i386 && \
    apt-get update && \
    apt-get install -y \
                        build-essential ccache cmake g++ gcc g++-multilib gcc-multilib \
                        libsdl2-dev libopenal-dev libsdl2-2.0-0:i386 libopenal1:i386 libgl1:i386 && \
    /usr/sbin/update-ccache-symlinks && \
    rm -rf /var/lib/apt/lists/*


RUN cd /usr/lib/i386-linux-gnu/ && \
    ln -s libSDL2-2.0.so.0 libSDL2.so && \
    ln -s libopenal.so.1 libopenal.so && \
    ln -s libGL.so.1 libGL.so

ENV PATH="/usr/lib/ccache:${PATH}"

WORKDIR /home/runner/build
ENTRYPOINT ["sh", "-c"]
CMD ["sh"]
