package sound

import "strconv"

var byName = make(map[string]ID)

func init() {
	for id, name := range soundNames {
		byName[name] = ID(id)
	}
}

func ByName(name string) ID {
	return byName[name]
}

type ID int

func (id ID) String() string {
	if id >= 0 || int(id) < len(soundNames) {
		return soundNames[id]
	}
	return "sound.ID(" + strconv.Itoa(int(id)) + ")"
}

func (id ID) GoString() string {
	if id >= 0 || int(id) < len(soundNames) {
		if id == 0 {
			return "sound.SoundNone"
		}
		return "sound.Sound" + soundNames[id]
	}
	return "sound.ID(" + strconv.Itoa(int(id)) + ")"
}

const (
	SoundNone = ID(iota)
	SoundAnchorCast
	SoundAnchorOn
	SoundAnchorOff
	SoundBlindCast
	SoundBlindOn
	SoundBlindOff
	SoundBlinkCast
	SoundBurnCast
	SoundCleansingFlameCast
	SoundChannelLifeCast
	SoundChannelLifeEffect
	SoundChannelLifeStop
	SoundCancelCast
	SoundCharmCast
	SoundCharmSuccess
	SoundCharmFailure
	SoundConfuseCast
	SoundConfuseOn
	SoundConfuseOff
	SoundCounterspellCast
	SoundCurePoisonCast
	SoundCurePoisonEffect
	SoundDeathCast
	SoundDeathOn
	SoundDeathOff
	SoundDeathTimer
	SoundDeathRayCast
	SoundDetonateGlyphCast
	SoundDrainManaCast
	SoundEarthquakeCast
	SoundEnergyBoltCast
	SoundEnergyBoltSustain
	SoundFearCast
	SoundFearOn
	SoundFearOff
	SoundForceOfNatureCast
	SoundForceOfNatureReflect
	SoundForceOfNatureRelease
	SoundGlyphCast
	SoundGlyphDetonate
	SoundFireballCast
	SoundFireballExplode
	SoundFirewalkCast
	SoundFirewalkOn
	SoundFirewalkOff
	SoundFirewalkFlame
	SoundFistCast
	SoundFistHit
	SoundForceFieldCast
	SoundFrostCast
	SoundFrostOn
	SoundFrostOff
	SoundFumbleCast
	SoundFumbleEffect
	SoundGreaterHealCast
	SoundGreaterHealEffect
	SoundGreaterHealStop
	SoundHasteCast
	SoundHasteOn
	SoundHasteOff
	SoundInfravisionCast
	SoundInfravisionOn
	SoundInfraVisionOff
	SoundInversionCast
	SoundInvisibilityCast
	SoundInvisibilityOn
	SoundInvisibilityOff
	SoundInvulnerabilityCast
	SoundInvulnerabilityOn
	SoundInvulnerabilityOff
	SoundInvulnerableEffect
	SoundLesserHealCast
	SoundLesserHealEffect
	SoundLightCast
	SoundLightOn
	SoundLightOff
	SoundLightningCast
	SoundLightningBolt
	SoundLockCast
	SoundManaBombCast
	SoundManaBombEffect
	SoundMarkCast
	SoundMagicMissileCast
	SoundMagicMissileDetonate
	SoundMeteorCast
	SoundMeteorShowerCast
	SoundMeteorHit
	SoundMoonglowCast
	SoundMoonglowOn
	SoundMoonglowOff
	SoundNullifyCast
	SoundNullifyOn
	SoundNullifyOff
	SoundPhantomCast
	SoundPixieSwarmCast
	SoundPixieHit
	SoundPlasmaCast
	SoundPlasmaSustain
	SoundPoisonCast
	SoundPoisonEffect
	SoundProtectionFromFireCast
	SoundProtectionFromFireOn
	SoundProtectionFromFireOff
	SoundProtectionFromFireEffect
	SoundProtectionFromElectricityCast
	SoundProtectionFromElectricityOn
	SoundProtectionFromElectricityOff
	SoundProtectionFromElectricityEffect
	SoundProtectionFromPoisonCast
	SoundProtectionFromPoisonOn
	SoundProtectionFromPoisonOff
	SoundProtectionFromPoisonEffect
	SoundProtectionFromMagicCast
	SoundProtectionFromMagicOn
	SoundProtectionFromMagicOff
	SoundProtectionFromMagicEffect
	SoundPullCast
	SoundPushCast
	SoundReflectiveShieldCast
	SoundReflectiveShieldOn
	SoundReflectiveShieldOff
	SoundReflectiveShieldEffect
	SoundRegenerationOn
	SoundRegenerationOff
	SoundRunCast
	SoundRunOn
	SoundRunOff
	SoundShieldCast
	SoundShieldOn
	SoundShieldOff
	SoundShieldRepelled
	SoundShockCast
	SoundShockOn
	SoundShockOff
	SoundShocked
	SoundSlowCast
	SoundSlowOn
	SoundSlowOff
	SoundStunCast
	SoundStunOn
	SoundStunOff
	SoundSummonCast
	SoundSwapCast
	SoundTagCast
	SoundTagOn
	SoundTagOff
	SoundTeleportOut
	SoundTeleportIn
	SoundTeleportToMarkerCast
	SoundTeleportToMarkerEffect
	SoundTeleportPopCast
	SoundTeleportToTargetCast
	SoundTelekinesisCast
	SoundTelekinesisOn
	SoundTelekinesisOff
	SoundToxicCloudCast
	SoundTriggerGlyphCast
	SoundTurnUndeadCast
	SoundTurnUndeadEffect
	SoundVampirismCast
	SoundVampirismOn
	SoundVampirismOff
	SoundDrainHealth
	SoundVillainCast
	SoundVillainOn
	SoundVillainOff
	SoundWallCast
	SoundWallOn
	SoundWallOff
	SoundBerserkerChargeInvoke
	SoundBerserkerCrash
	SoundBerserkerChargeOn
	SoundBerserkerChargeOff
	SoundWarcryInvoke
	SoundWarcryOn
	SoundWarcryOff
	SoundHarpoonInvoke
	SoundHarpoonOn
	SoundHarpoonOff
	SoundTreadLightlyInvoke
	SoundTreadLightlyOn
	SoundTreadLightlyOff
	SoundEyeOfTheWolfInvoke
	SoundEyeOfTheWolfOn
	SoundEyeOfTheWolfOff
	SoundSpellPhonemeUp
	SoundSpellPhonemeUpRight
	SoundSpellPhonemeRight
	SoundSpellPhonemeDownRight
	SoundSpellPhonemeDown
	SoundSpellPhonemeDownLeft
	SoundSpellPhonemeLeft
	SoundSpellPhonemeUpLeft
	SoundFemaleSpellPhonemeUp
	SoundFemaleSpellPhonemeUpRight
	SoundFemaleSpellPhonemeRight
	SoundFemaleSpellPhonemeDownRight
	SoundFemaleSpellPhonemeDown
	SoundFemaleSpellPhonemeDownLeft
	SoundFemaleSpellPhonemeLeft
	SoundFemaleSpellPhonemeUpLeft
	SoundNPCSpellPhonemeUp
	SoundNPCSpellPhonemeUpRight
	SoundNPCSpellPhonemeRight
	SoundNPCSpellPhonemeDownRight
	SoundNPCSpellPhonemeDown
	SoundNPCSpellPhonemeDownLeft
	SoundNPCSpellPhonemeLeft
	SoundNPCSpellPhonemeUpLeft
	SoundNPCFemaleSpellPhonemeUp
	SoundNPCFemaleSpellPhonemeUpRight
	SoundNPCFemaleSpellPhonemeRight
	SoundNPCFemaleSpellPhonemeDownRight
	SoundNPCFemaleSpellPhonemeDown
	SoundNPCFemaleSpellPhonemeDownLeft
	SoundNPCFemaleSpellPhonemeLeft
	SoundNPCFemaleSpellPhonemeUpLeft
	SoundFireballWand
	SoundSmallFireballWand
	SoundFlareWand
	SoundLightningWand
	SoundDepletedWand
	SoundRicochet
	SoundWeaponEffectFire
	SoundWeaponEffectElectricity
	SoundAwardSpell
	SoundAwardGuide
	SoundBlueFireDamage
	SoundDrainMana
	SoundManaRecharge
	SoundPermanentFizzle
	SoundManaEmpty
	SoundLock
	SoundUnlock
	SoundElevEnable
	SoundElevDisable
	SoundOpenWoodenDoor
	SoundMoveWoodenDoor
	SoundCloseWoodenDoor
	SoundWoodenDoorLocked
	SoundOpenGate
	SoundMoveGate
	SoundCloseGate
	SoundGateLocked
	SoundOpenWoodenGate
	SoundCloseWoodenGate
	SoundOpenHeavyWoodenDoor
	SoundCloseHeavyWoodenDoor
	SoundElevStoneUp
	SoundElevStoneDown
	SoundElevWoodUp
	SoundElevWoodDown
	SoundElevMechUp
	SoundElevMechDown
	SoundElevLavaUp
	SoundElevLavaDown
	SoundElevGreenUp
	SoundElevGreenDown
	SoundElevLOTDUp
	SoundElevLOTDDown
	SoundGear1
	SoundGear2
	SoundGear3
	SoundSmallRockMove
	SoundMediumRockMove
	SoundLargeRockMove
	SoundBoulderMove
	SoundWalkOnSnow
	SoundWalkOnStone
	SoundWalkOnDirt
	SoundWalkOnWood
	SoundWalkOnWater
	SoundWalkOnMud
	SoundRunOnSnow
	SoundRunOnStone
	SoundRunOnDirt
	SoundRunOnWood
	SoundRunOnWater
	SoundRunOnMud
	SoundPlayerFallThud
	SoundBarrelMove
	SoundBlackPowderBurn
	SoundFireExtinguish
	SoundPolypExplode
	SoundPowderBarrelExplode
	SoundBarrelBreak
	SoundWaterBarrelBreak
	SoundLOTDBarrelBreak
	SoundWineCaskBreak
	SoundBarrelStackBreak
	SoundCoffinBreak
	SoundWaspHiveBreak
	SoundWorkstationBreak
	SoundCrushLight
	SoundCrushMedium
	SoundCrushHard
	SoundSentryRayHitWall
	SoundSentryRayHit
	SoundDeathRayKill
	SoundTauntLaugh
	SoundTauntShakeFist
	SoundTauntPoint
	SoundFlagPickup
	SoundFlagDrop
	SoundFlagRespawn
	SoundFlagCapture
	SoundTreasurePickup
	SoundTreasureDrop
	SoundGameOver
	SoundServerOptionsChange
	SoundCamperAlarm
	SoundPlayerEliminated
	SoundCrownChange
	SoundHumanMaleEatFood
	SoundHumanMaleEatApple
	SoundHumanMaleDrinkJug
	SoundHumanMaleHurtLight
	SoundHumanMaleHurtMedium
	SoundHumanMaleHurtHeavy
	SoundHumanMaleHurtPoison
	SoundHumanMaleDie
	SoundHumanMaleExertionLight
	SoundHumanMaleExertionHeavy
	SoundHumanFemaleEatFood
	SoundHumanFemaleEatApple
	SoundHumanFemaleDrinkJug
	SoundHumanFemaleHurtLight
	SoundHumanFemaleHurtMedium
	SoundHumanFemaleHurtHeavy
	SoundHumanFemaleHurtPoison
	SoundHumanFemaleDie
	SoundHumanFemaleExertionLight
	SoundHumanFemaleExertionHeavy
	SoundMonsterEatFood
	SoundBatMove
	SoundBatBite
	SoundBatDie
	SoundBatRecognize
	SoundSmallSpiderMove
	SoundSmallSpiderIdle
	SoundSmallSpiderBite
	SoundSmallSpiderDie
	SoundSmallSpiderRecognize
	SoundLargeSpiderMove
	SoundLargeSpiderIdle
	SoundLargeSpiderBite
	SoundLargeSpiderDie
	SoundLargeSpiderSpit
	SoundLargeSpiderRecognize
	SoundLargeSpiderHurt
	SoundWebGooHit
	SoundSkeletonMove
	SoundSkeletonAttackInit
	SoundSkeletonHitting
	SoundSkeletonMissing
	SoundSkeletonDie
	SoundSkeletonRecognize
	SoundSkeletonHurt
	SoundSkeletonLordMove
	SoundSkeletonLordAttackInit
	SoundSkeletonLordHitting
	SoundSkeletonLordMissing
	SoundSkeletonLordDie
	SoundSkeletonLordRecognize
	SoundSkeletonLordHurt
	SoundBomberRecognize
	SoundBomberSummon
	SoundBomberDie
	SoundBomberMove
	SoundDemonRecognize
	SoundDemonTaunt
	SoundDemonSpellInit
	SoundDemonDie
	SoundDemonMove
	SoundDemonHurt
	SoundGruntMove
	SoundGruntTaunt
	SoundGruntIdle
	SoundGruntAttackInit
	SoundGruntHitting
	SoundGruntMissing
	SoundGruntDie
	SoundGruntBowTwang
	SoundGruntRecognize
	SoundGruntHurt
	SoundOgreBruteListen
	SoundOgreBruteTaunt
	SoundOgreBruteIdle
	SoundOgreBruteEngage
	SoundOgreBruteRecognize
	SoundOgreBruteMove
	SoundOgreBruteHurt
	SoundOgreBruteDie
	SoundOgreBruteMeleeHit
	SoundOgreBruteMeleeMiss
	SoundOgreBruteAttackInit
	SoundOgreWarlordListen
	SoundOgreWarlordTaunt
	SoundOgreWarlordIdle
	SoundOgreWarlordEngage
	SoundOgreWarlordRecognize
	SoundOgreWarlordMove
	SoundOgreWarlordHurt
	SoundOgreWarlordDie
	SoundOgreWarlordMeleeHit
	SoundOgreWarlordMeleeMiss
	SoundOgreWarlordAttackInit
	SoundOgreWarlordThrow
	SoundScorpionRecognize
	SoundScorpionMove
	SoundScorpionIdle
	SoundScorpionAttackInit
	SoundScorpionStingHit
	SoundScorpionStingMiss
	SoundScorpionClawHit
	SoundScorpionClawMiss
	SoundScorpionHurt
	SoundScorpionDie
	SoundLeechMove
	SoundLeechIdle
	SoundLeechAttackInit
	SoundLeechHitting
	SoundLeechMissing
	SoundLeechDie
	SoundLeechRecognize
	SoundLeechHurt
	SoundBearMove
	SoundBearAttackInit
	SoundBearHitting
	SoundBearMissing
	SoundBearDie
	SoundBearRecognize
	SoundBearHurt
	SoundWolfMove
	SoundWolfIdle
	SoundWolfAttackInit
	SoundWolfHitting
	SoundWolfMissing
	SoundWolfDie
	SoundWolfRecognize
	SoundWolfHurt
	SoundWolfHowl
	SoundWolfGrowl
	SoundPlantSleep
	SoundPlantAttackInit
	SoundPlantHitting
	SoundPlantMissing
	SoundPlantDie
	SoundPlantRecognize
	SoundPlantHurt
	SoundPlantGrowl
	SoundMimicMove
	SoundMimicIdle
	SoundMimicAttackInit
	SoundMimicHitting
	SoundMimicMissing
	SoundMimicDie
	SoundMimicRecognize
	SoundMimicHurt
	SoundMimicMorph
	SoundZombieMove
	SoundZombieIdle
	SoundZombieAttackInit
	SoundZombieHitting
	SoundZombieMissing
	SoundZombieDie
	SoundZombieRecognize
	SoundZombieHurt
	SoundZombieGetUp
	SoundVileZombieMove
	SoundVileZombieIdle
	SoundVileZombieAttackInit
	SoundVileZombieHitting
	SoundVileZombieMissing
	SoundVileZombieDie
	SoundVileZombieRecognize
	SoundVileZombieHurt
	SoundVileZombieGetUp
	SoundImpMove
	SoundImpShoot
	SoundImpSteal
	SoundImpDie
	SoundImpRecognize
	SoundGolemMove
	SoundGolemHitting
	SoundGolemMissing
	SoundGolemDie
	SoundGolemHurt
	SoundGolemRecognize
	SoundMechGolemMove
	SoundMechGolemAttackInit
	SoundMechGolemHitting
	SoundMechGolemMissing
	SoundMechGolemDie
	SoundMechGolemHurt
	SoundMechGolemRecognize
	SoundTowerRecognize
	SoundTowerShoot
	SoundSkullRecognize
	SoundSkullShoot
	SoundGhostMove
	SoundGhostHitting
	SoundGhostDie
	SoundGhostHurt
	SoundGhostRecognize
	SoundWizardTalkable
	SoundWizardMove
	SoundWizardDie
	SoundWizardHurt
	SoundWizardRecognize
	SoundWizardEngage
	SoundWizardRetreat
	SoundWaspMove
	SoundWaspIdle
	SoundWaspSting
	SoundWaspDie
	SoundWaspRecognize
	SoundEmberDemonMove
	SoundEmberDemonTaunt
	SoundEmberDemonHitting
	SoundEmberDemonMissing
	SoundEmberDemonDie
	SoundEmberDemonThrow
	SoundEmberDemonRecognize
	SoundEmberDemonHurt
	SoundUrchinMove
	SoundUrchinTaunt
	SoundUrchinIdle
	SoundUrchinDie
	SoundUrchinThrow
	SoundUrchinRecognize
	SoundUrchinHurt
	SoundUrchinFlee
	SoundUrchinShamanMove
	SoundUrchinShamanTaunt
	SoundUrchinShamanIdle
	SoundUrchinShamanDie
	SoundUrchinShamanRecognize
	SoundUrchinShamanHurt
	SoundUrchinShamanFlee
	SoundArcherMove
	SoundArcherTaunt
	SoundArcherIdle
	SoundArcherDie
	SoundArcherMissileInit
	SoundArcherShoot
	SoundArcherRecognize
	SoundArcherHurt
	SoundArcherRetreat
	SoundSwordsmanMove
	SoundSwordsmanTaunt
	SoundSwordsmanIdle
	SoundSwordsmanAttackInit
	SoundSwordsmanHitting
	SoundSwordsmanMissing
	SoundSwordsmanDie
	SoundSwordsmanRecognize
	SoundSwordsmanHurt
	SoundSwordsmanRetreat
	SoundBeholderMove
	SoundBeholderIdle
	SoundBeholderAttackInit
	SoundBeholderDie
	SoundBeholderRecognize
	SoundBeholderHurt
	SoundDryadMove
	SoundDryadTaunt
	SoundDryadDie
	SoundDryadRecognize
	SoundDryadHurt
	SoundEvilCherubMove
	SoundEvilCherubTaunt
	SoundEvilCherubIdle
	SoundEvilCherubMissileInit
	SoundEvilCherubShoot
	SoundEvilCherubDie
	SoundEvilCherubRecognize
	SoundEvilCherubHurt
	SoundFishDie
	SoundFrogDie
	SoundFrogRecognize
	SoundHecubahTaunt
	SoundHecubahTalkable
	SoundHecubahMove
	SoundHecubahAttackInit
	SoundHecubahDie
	SoundHecubahRecognize
	SoundHecubahHurt
	SoundHecubahDieFrame0A
	SoundHecubahDieFrame0B
	SoundHecubahDieFrame98
	SoundHecubahDieFrame194
	SoundHecubahDieFrame283
	SoundHecubahDieFrame439
	SoundNecromancerTaunt
	SoundNecromancerTalkable
	SoundNecromancerMove
	SoundNecromancerAttackInit
	SoundNecromancerDie
	SoundNecromancerRecognize
	SoundNecromancerEngage
	SoundNecromancerRetreat
	SoundNecromancerHurt
	SoundLichMove
	SoundLichAttackInit
	SoundLichDie
	SoundLichRecognize
	SoundLichHurt
	SoundFlyingGolemMove
	SoundFlyingGolemShoot
	SoundFlyingGolemDie
	SoundFlyingGolemRecognize
	SoundFlyingGolemHurt
	SoundNPCTalkable
	SoundNPCIdle
	SoundNPCDie
	SoundNPCRecognize
	SoundNPCRetreat
	SoundNPCHurt
	SoundMaidenIdle
	SoundMaidenTalkable
	SoundMaidenFlee
	SoundMaidenDie
	SoundMaidenHurt
	SoundRatDie
	SoundShadeMove
	SoundShadeAttackInit
	SoundShadeDie
	SoundShadeRecognize
	SoundShadeHurt
	SoundWeirdlingMove
	SoundWillOWispMove
	SoundWillOWispIdle
	SoundWillOWispDie
	SoundWillOWispHurt
	SoundWillOWispRecognize
	SoundWillOWispEngage
	SoundTrollMove
	SoundTrollIdle
	SoundTrollDie
	SoundTrollHurt
	SoundTrollRecognize
	SoundTrollAttackInit
	SoundTrollFlatus
	SoundMaleNPC1Talkable
	SoundMaleNPC1Idle
	SoundMaleNPC1Recognize
	SoundMaleNPC1Engage
	SoundMaleNPC1Retreat
	SoundMaleNPC1Hurt
	SoundMaleNPC1Die
	SoundMaleNPC1AttackInit
	SoundMaleNPC2Talkable
	SoundMaleNPC2Idle
	SoundMaleNPC2Recognize
	SoundMaleNPC2Engage
	SoundMaleNPC2Retreat
	SoundMaleNPC2Hurt
	SoundMaleNPC2Die
	SoundMaleNPC2AttackInit
	SoundMaiden1Talkable
	SoundMaiden1Idle
	SoundMaiden1Recognize
	SoundMaiden1Retreat
	SoundMaiden1Hurt
	SoundMaiden1Die
	SoundMaiden1AttackInit
	SoundMaiden2Talkable
	SoundMaiden2Idle
	SoundMaiden2Recognize
	SoundMaiden2Retreat
	SoundMaiden2Hurt
	SoundMaiden2Die
	SoundMaiden2AttackInit
	SoundHorvathTalkable
	SoundHorvathEngage
	SoundHorvathHurt
	SoundHorvathDie
	SoundWizard1Talkable
	SoundWizard1Idle
	SoundWizard1Recognize
	SoundWizard1Engage
	SoundWizard1Retreat
	SoundWizard1Hurt
	SoundWizard1Die
	SoundWizard1AttackInit
	SoundWizard2Talkable
	SoundWizard2Idle
	SoundWizard2Recognize
	SoundWizard2Engage
	SoundWizard2Retreat
	SoundWizard2Hurt
	SoundWizard2Die
	SoundWizard2AttackInit
	SoundFireKnight1Talkable
	SoundFireKnight1Idle
	SoundFireKnight1Recognize
	SoundFireKnight1Engage
	SoundFireKnight1Retreat
	SoundFireKnight1Hurt
	SoundFireKnight1Die
	SoundFireKnight1AttackInit
	SoundFireKnight2Talkable
	SoundFireKnight2Idle
	SoundFireKnight2Recognize
	SoundFireKnight2Engage
	SoundFireKnight2Retreat
	SoundFireKnight2Hurt
	SoundFireKnight2Die
	SoundFireKnight2AttackInit
	SoundGuard1Talkable
	SoundGuard1Idle
	SoundGuard1Recognize
	SoundGuard1Engage
	SoundGuard1Retreat
	SoundGuard1Hurt
	SoundGuard1Die
	SoundGuard1AttackInit
	SoundGuard2Talkable
	SoundGuard2Idle
	SoundGuard2Recognize
	SoundGuard2Engage
	SoundGuard2Retreat
	SoundGuard2Hurt
	SoundGuard2Die
	SoundGuard2AttackInit
	SoundWoundedNPCTalkable
	SoundWoundedNPCIdle
	SoundWoundedNPCRecognize
	SoundWoundedNPCRetreat
	SoundWoundedNPCHurt
	SoundWoundedNPCDie
	SoundWoundedNPCAttackInit
	SoundHorrendousTalkable
	SoundHorrendousRecognize
	SoundHorrendousRetreat
	SoundHorrendousHurt
	SoundHorrendousDie
	SoundHorrendousAttackInit
	SoundSecretWallOpen
	SoundSecretWallClose
	SoundSecretWallEarthOpen
	SoundSecretWallEarthClose
	SoundSecretWallMetalOpen
	SoundSecretWallMetalClose
	SoundSecretWallStoneOpen
	SoundSecretWallStoneClose
	SoundSecretWallWoodOpen
	SoundSecretWallWoodClose
	SoundTriggerPressed
	SoundTriggerReleased
	SoundPotionUse
	SoundPotionBreak
	SoundRestoreHealth
	SoundRestoreMana
	SoundWallDestroyed
	SoundWallDestroyedStone
	SoundWallDestroyedWood
	SoundWallDestroyedMetal
	SoundChestOpen
	SoundCryptChestOpen
	SoundSackChestOpen
	SoundChestLocked
	SoundEggBreak
	SoundPoisoned
	SoundButtonPress
	SoundButtonRelease
	SoundLeverToggle
	SoundSwitchToggle
	SoundChainPull
	SoundShortBellsUp
	SoundLongBellsUp
	SoundLongBellsDown
	SoundBigBell
	SoundMetallicBong
	SoundChime
	SoundBigGong
	SoundSmallGong
	SoundMysticChant
	SoundTripleChime
	SoundClank1
	SoundClank2
	SoundClank3
	SoundMapOpen
	SoundMapClose
	SoundBookOpen
	SoundBookClose
	SoundPageTurn
	SoundInventoryOpen
	SoundInventoryClose
	SoundInventoryPickup
	SoundInventoryDrop
	SoundSpellPickup
	SoundSpellDrop
	SoundSpellPopOffBook
	SoundTrapEditorOpen
	SoundTrapEditorClose
	SoundChangeSpellbar
	SoundExpandSpellbar
	SoundCollapseSpellbar
	SoundCreatureCageAppears
	SoundCreatureCageHides
	SoundShopRepairItem
	SoundMetalArmorPickup
	SoundMetalArmorDrop
	SoundMetalArmorBreak
	SoundLeatherArmorPickup
	SoundLeatherArmorDrop
	SoundLeatherArmorBreak
	SoundWoodenArmorPickup
	SoundWoodenArmorDrop
	SoundWoodenArmorBreak
	SoundClothArmorPickup
	SoundClothArmorDrop
	SoundClothArmorBreak
	SoundShoesPickup
	SoundShoesDrop
	SoundMetalWeaponBreak
	SoundWoodWeaponBreak
	SoundKeyPickup
	SoundKeyDrop
	SoundAmuletPickup
	SoundAmuletDrop
	SoundTrapPickup
	SoundTrapDrop
	SoundBookPickup
	SoundBookDrop
	SoundScrollPickup
	SoundScrollDrop
	SoundWandPickup
	SoundWandDrop
	SoundPotionPickup
	SoundPotionDrop
	SoundMeatPickup
	SoundMeatDrop
	SoundApplePickup
	SoundAppleDrop
	SoundShroomPickup
	SoundShroomDrop
	SoundSpectaclesPickup
	SoundSpectaclesDrop
	SoundMetalWeaponPickup
	SoundMetalWeaponDrop
	SoundWoodenWeaponPickup
	SoundWoodenWeaponDrop
	SoundBearTrapTriggered
	SoundPoisonTrapTriggered
	SoundStoneHitStone
	SoundStoneHitEarth
	SoundStoneHitWood
	SoundStoneHitMetal
	SoundStoneHitFlesh
	SoundWoodHitStone
	SoundWoodHitEarth
	SoundWoodHitWood
	SoundWoodHitMetal
	SoundWoodHitFlesh
	SoundMetalHitStone
	SoundMetalHitEarth
	SoundMetalHitWood
	SoundMetalHitMetal
	SoundMetalHitFlesh
	SoundFleshHitStone
	SoundFleshHitEarth
	SoundFleshHitWood
	SoundFleshHitMetal
	SoundFleshHitFlesh
	SoundDiamondHitStone
	SoundDiamondHitEarth
	SoundDiamondHitWood
	SoundDiamondHitMetal
	SoundDiamondHitFlesh
	SoundHitStoneBreakable
	SoundHitEarthBreakable
	SoundHitWoodBreakable
	SoundHitMetalBreakable
	SoundHitMagicBreakable
	SoundHitMetalShield
	SoundPunchMissing
	SoundLongswordMissing
	SoundSwordMissing
	SoundHammerMissing
	SoundAxeMissing
	SoundMaceMissing
	SoundBowShoot
	SoundCrossBowShoot
	SoundBowEmpty
	SoundCrossBowEmpty
	SoundArrowTrapShoot
	SoundGreatSwordReflect
	SoundChakramThrow
	SoundChakramCatch
	SoundChakramFallToGround
	SoundStaffBlock
	SoundNextWeapon
	SoundHeartBeat
	SoundGenerateTick
	SoundSummonClick
	SoundSummonComplete
	SoundSummonAbort
	SoundManaClick
	SoundLevelUp
	SoundJournalEntryAdd
	SoundSecretFound
	SoundEarthRumbleMajor
	SoundEarthRumbleMinor
	SoundElectricalArc1
	SoundFloorSpikesUp
	SoundFloorSpikesDown
	SoundSpikeBlockMove
	SoundBoulderRoll
	SoundArcheryContestBegins
	SoundHorrendousIsKilled
	SoundStaffOblivionAchieve1
	SoundStaffOblivionAchieve2
	SoundStaffOblivionAchieve3
	SoundStaffOblivionAchieve4
	SoundFireGrate
	SoundMechGolemPowerUp
	SoundShellSelect
	SoundShellClick
	SoundShellSlideIn
	SoundShellSlideOut
	SoundShellMouseBoom
	SoundNoCanDo
	SoundBallThrow
	SoundBallGrab
	SoundBallBounce
	SoundBallHitGoal
	SoundBirdAmbient1
	SoundLoopAmbienceCastle
	SoundLoopAmbienceCave
	SoundLoopAmbienceForest
	SoundLoopAmbienceInferno
	SoundLoopAmbienceLOTD
	SoundLoopAmbienceMine
	SoundLoopAmbienceSwamp
	SoundLoopAmbBird2
	SoundLoopAmbBirdSwamp1
	SoundLoopAmbBirdSwamp2
	SoundLoopAmbBrook2
	SoundLoopAmbBrook3
	SoundLoopAmbCricket1
	SoundLoopAmbCricket2
	SoundLoopAmbCricket3
	SoundLoopAmbCrow1
	SoundLoopAmbCrow2
	SoundLoopAmbCrowWL
	SoundLoopAmbDog1
	SoundLoopAmbDripCave1
	SoundLoopAmbDripCave2
	SoundLoopAmbDripRoom
	SoundLoopAmbFrogSwamp1
	SoundLoopAmbFrogSwamp2
	SoundLoopAmbFrogSwamp3
	SoundLoopAmbFrogSwamp4
	SoundLoopAmbFrogSwamp5
	SoundLoopAmbFliesSwamp
	SoundLoopAmbRodentForest1
	SoundLoopAmbRodentForest2
	SoundLoopAmbCaveRumble
	SoundLoopAmbSpiritsFOV
	SoundLoopAmbSpiritsLOTD
	SoundLoopAmbWindCave1
	SoundLoopAmbWindCave2
	SoundLoopAmbWindCave3
	SoundLoopAmbWindLOTD
	SoundLoopAmbWindWL1
	SoundLoopAmbWindWL2
	SoundLoopAmbHeartNox
	SoundLoopAmbBird3
	SoundLoopAmbBird4
	SoundLoopAmbBird5
	SoundLoopAmbBird6
	SoundLoopAmbBird7
	SoundLoopAmbBird8
	SoundLoopAmbIxTemple
	SoundLoopAmbLeaves
	SoundLoopAmbHowls
	SoundLoopAmbWeirdling
	SoundLoopAmbSpikeWave
	SoundLoopAmbBeachBirds
	SoundLoopAmbBeachWaves
	SoundLoopCampfire
	SoundLoopTorch
	SoundLoopBlueFire
	SoundLoopWorkstation
	SoundLoopWaterFountain
	SoundLoopWindmill
	SoundLoopOrrery
	SoundLoopVandegraf
	SoundLoopGearSmall
	SoundLoopGearLarge
	SoundLoopGearPulley
	SoundLoopPolyp
	SoundLoopSentryGlobe
	SoundLoopSpikePillar
	SoundHarpoonBroken
	SoundHarpoonReel
	SoundMonsterGeneratorDie
	SoundMonsterGeneratorHurt
	SoundMonsterGeneratorSpawn
	SoundPlayerExit
	SoundAwardLife
	SoundSoulGateTouch
	SoundQuestRespawn
	SoundQuestFinalDeath
	SoundQuestPlayerJoinGame
	SoundQuestStatScreen
	SoundQuestIntroScreen
	SoundQuestPlayerExitGame
	SoundQuestLockedChest
	SoundLoopMonsterGenerator
	SoundStoneDoorOpen
	SoundStoneDoorClose
	SoundDiamondDrop
	SoundDiamondPickup
	SoundRubyDrop
	SoundRubyPickup
	SoundEmeraldDrop
	SoundEmeraldPickup
	SoundEnableSharedKeyMode
)

var soundNames = []string{
	"NULL",
	"AnchorCast",
	"AnchorOn",
	"AnchorOff",
	"BlindCast",
	"BlindOn",
	"BlindOff",
	"BlinkCast",
	"BurnCast",
	"CleansingFlameCast",
	"ChannelLifeCast",
	"ChannelLifeEffect",
	"ChannelLifeStop",
	"CancelCast",
	"CharmCast",
	"CharmSuccess",
	"CharmFailure",
	"ConfuseCast",
	"ConfuseOn",
	"ConfuseOff",
	"CounterspellCast",
	"CurePoisonCast",
	"CurePoisonEffect",
	"DeathCast",
	"DeathOn",
	"DeathOff",
	"DeathTimer",
	"DeathRayCast",
	"DetonateGlyphCast",
	"DrainManaCast",
	"EarthquakeCast",
	"EnergyBoltCast",
	"EnergyBoltSustain",
	"FearCast",
	"FearOn",
	"FearOff",
	"ForceOfNatureCast",
	"ForceOfNatureReflect",
	"ForceOfNatureRelease",
	"GlyphCast",
	"GlyphDetonate",
	"FireballCast",
	"FireballExplode",
	"FirewalkCast",
	"FirewalkOn",
	"FirewalkOff",
	"FirewalkFlame",
	"FistCast",
	"FistHit",
	"ForceFieldCast",
	"FrostCast",
	"FrostOn",
	"FrostOff",
	"FumbleCast",
	"FumbleEffect",
	"GreaterHealCast",
	"GreaterHealEffect",
	"GreaterHealStop",
	"HasteCast",
	"HasteOn",
	"HasteOff",
	"InfravisionCast",
	"InfravisionOn",
	"InfraVisionOff",
	"InversionCast",
	"InvisibilityCast",
	"InvisibilityOn",
	"InvisibilityOff",
	"InvulnerabilityCast",
	"InvulnerabilityOn",
	"InvulnerabilityOff",
	"InvulnerableEffect",
	"LesserHealCast",
	"LesserHealEffect",
	"LightCast",
	"LightOn",
	"LightOff",
	"LightningCast",
	"LightningBolt",
	"LockCast",
	"ManaBombCast",
	"ManaBombEffect",
	"MarkCast",
	"MagicMissileCast",
	"MagicMissileDetonate",
	"MeteorCast",
	"MeteorShowerCast",
	"MeteorHit",
	"MoonglowCast",
	"MoonglowOn",
	"MoonglowOff",
	"NullifyCast",
	"NullifyOn",
	"NullifyOff",
	"PhantomCast",
	"PixieSwarmCast",
	"PixieHit",
	"PlasmaCast",
	"PlasmaSustain",
	"PoisonCast",
	"PoisonEffect",
	"ProtectionFromFireCast",
	"ProtectionFromFireOn",
	"ProtectionFromFireOff",
	"ProtectionFromFireEffect",
	"ProtectionFromElectricityCast",
	"ProtectionFromElectricityOn",
	"ProtectionFromElectricityOff",
	"ProtectionFromElectricityEffect",
	"ProtectionFromPoisonCast",
	"ProtectionFromPoisonOn",
	"ProtectionFromPoisonOff",
	"ProtectionFromPoisonEffect",
	"ProtectionFromMagicCast",
	"ProtectionFromMagicOn",
	"ProtectionFromMagicOff",
	"ProtectionFromMagicEffect",
	"PullCast",
	"PushCast",
	"ReflectiveShieldCast",
	"ReflectiveShieldOn",
	"ReflectiveShieldOff",
	"ReflectiveShieldEffect",
	"RegenerationOn",
	"RegenerationOff",
	"RunCast",
	"RunOn",
	"RunOff",
	"ShieldCast",
	"ShieldOn",
	"ShieldOff",
	"ShieldRepelled",
	"ShockCast",
	"ShockOn",
	"ShockOff",
	"Shocked",
	"SlowCast",
	"SlowOn",
	"SlowOff",
	"StunCast",
	"StunOn",
	"StunOff",
	"SummonCast",
	"SwapCast",
	"TagCast",
	"TagOn",
	"TagOff",
	"TeleportOut",
	"TeleportIn",
	"TeleportToMarkerCast",
	"TeleportToMarkerEffect",
	"TeleportPopCast",
	"TeleportToTargetCast",
	"TelekinesisCast",
	"TelekinesisOn",
	"TelekinesisOff",
	"ToxicCloudCast",
	"TriggerGlyphCast",
	"TurnUndeadCast",
	"TurnUndeadEffect",
	"VampirismCast",
	"VampirismOn",
	"VampirismOff",
	"DrainHealth",
	"VillainCast",
	"VillainOn",
	"VillainOff",
	"WallCast",
	"WallOn",
	"WallOff",
	"BerserkerChargeInvoke",
	"BerserkerCrash",
	"BerserkerChargeOn",
	"BerserkerChargeOff",
	"WarcryInvoke",
	"WarcryOn",
	"WarcryOff",
	"HarpoonInvoke",
	"HarpoonOn",
	"HarpoonOff",
	"TreadLightlyInvoke",
	"TreadLightlyOn",
	"TreadLightlyOff",
	"EyeOfTheWolfInvoke",
	"EyeOfTheWolfOn",
	"EyeOfTheWolfOff",
	"SpellPhonemeUp",
	"SpellPhonemeUpRight",
	"SpellPhonemeRight",
	"SpellPhonemeDownRight",
	"SpellPhonemeDown",
	"SpellPhonemeDownLeft",
	"SpellPhonemeLeft",
	"SpellPhonemeUpLeft",
	"FemaleSpellPhonemeUp",
	"FemaleSpellPhonemeUpRight",
	"FemaleSpellPhonemeRight",
	"FemaleSpellPhonemeDownRight",
	"FemaleSpellPhonemeDown",
	"FemaleSpellPhonemeDownLeft",
	"FemaleSpellPhonemeLeft",
	"FemaleSpellPhonemeUpLeft",
	"NPCSpellPhonemeUp",
	"NPCSpellPhonemeUpRight",
	"NPCSpellPhonemeRight",
	"NPCSpellPhonemeDownRight",
	"NPCSpellPhonemeDown",
	"NPCSpellPhonemeDownLeft",
	"NPCSpellPhonemeLeft",
	"NPCSpellPhonemeUpLeft",
	"NPCFemaleSpellPhonemeUp",
	"NPCFemaleSpellPhonemeUpRight",
	"NPCFemaleSpellPhonemeRight",
	"NPCFemaleSpellPhonemeDownRight",
	"NPCFemaleSpellPhonemeDown",
	"NPCFemaleSpellPhonemeDownLeft",
	"NPCFemaleSpellPhonemeLeft",
	"NPCFemaleSpellPhonemeUpLeft",
	"FireballWand",
	"SmallFireballWand",
	"FlareWand",
	"LightningWand",
	"DepletedWand",
	"Ricochet",
	"WeaponEffectFire",
	"WeaponEffectElectricity",
	"AwardSpell",
	"AwardGuide",
	"BlueFireDamage",
	"DrainMana",
	"ManaRecharge",
	"PermanentFizzle",
	"ManaEmpty",
	"Lock",
	"Unlock",
	"ElevEnable",
	"ElevDisable",
	"OpenWoodenDoor",
	"MoveWoodenDoor",
	"CloseWoodenDoor",
	"WoodenDoorLocked",
	"OpenGate",
	"MoveGate",
	"CloseGate",
	"GateLocked",
	"OpenWoodenGate",
	"CloseWoodenGate",
	"OpenHeavyWoodenDoor",
	"CloseHeavyWoodenDoor",
	"ElevStoneUp",
	"ElevStoneDown",
	"ElevWoodUp",
	"ElevWoodDown",
	"ElevMechUp",
	"ElevMechDown",
	"ElevLavaUp",
	"ElevLavaDown",
	"ElevGreenUp",
	"ElevGreenDown",
	"ElevLOTDUp",
	"ElevLOTDDown",
	"Gear1",
	"Gear2",
	"Gear3",
	"SmallRockMove",
	"MediumRockMove",
	"LargeRockMove",
	"BoulderMove",
	"WalkOnSnow",
	"WalkOnStone",
	"WalkOnDirt",
	"WalkOnWood",
	"WalkOnWater",
	"WalkOnMud",
	"RunOnSnow",
	"RunOnStone",
	"RunOnDirt",
	"RunOnWood",
	"RunOnWater",
	"RunOnMud",
	"PlayerFallThud",
	"BarrelMove",
	"BlackPowderBurn",
	"FireExtinguish",
	"PolypExplode",
	"PowderBarrelExplode",
	"BarrelBreak",
	"WaterBarrelBreak",
	"LOTDBarrelBreak",
	"WineCaskBreak",
	"BarrelStackBreak",
	"CoffinBreak",
	"WaspHiveBreak",
	"WorkstationBreak",
	"CrushLight",
	"CrushMedium",
	"CrushHard",
	"SentryRayHitWall",
	"SentryRayHit",
	"DeathRayKill",
	"TauntLaugh",
	"TauntShakeFist",
	"TauntPoint",
	"FlagPickup",
	"FlagDrop",
	"FlagRespawn",
	"FlagCapture",
	"TreasurePickup",
	"TreasureDrop",
	"GameOver",
	"ServerOptionsChange",
	"CamperAlarm",
	"PlayerEliminated",
	"CrownChange",
	"HumanMaleEatFood",
	"HumanMaleEatApple",
	"HumanMaleDrinkJug",
	"HumanMaleHurtLight",
	"HumanMaleHurtMedium",
	"HumanMaleHurtHeavy",
	"HumanMaleHurtPoison",
	"HumanMaleDie",
	"HumanMaleExertionLight",
	"HumanMaleExertionHeavy",
	"HumanFemaleEatFood",
	"HumanFemaleEatApple",
	"HumanFemaleDrinkJug",
	"HumanFemaleHurtLight",
	"HumanFemaleHurtMedium",
	"HumanFemaleHurtHeavy",
	"HumanFemaleHurtPoison",
	"HumanFemaleDie",
	"HumanFemaleExertionLight",
	"HumanFemaleExertionHeavy",
	"MonsterEatFood",
	"BatMove",
	"BatBite",
	"BatDie",
	"BatRecognize",
	"SmallSpiderMove",
	"SmallSpiderIdle",
	"SmallSpiderBite",
	"SmallSpiderDie",
	"SmallSpiderRecognize",
	"LargeSpiderMove",
	"LargeSpiderIdle",
	"LargeSpiderBite",
	"LargeSpiderDie",
	"LargeSpiderSpit",
	"LargeSpiderRecognize",
	"LargeSpiderHurt",
	"WebGooHit",
	"SkeletonMove",
	"SkeletonAttackInit",
	"SkeletonHitting",
	"SkeletonMissing",
	"SkeletonDie",
	"SkeletonRecognize",
	"SkeletonHurt",
	"SkeletonLordMove",
	"SkeletonLordAttackInit",
	"SkeletonLordHitting",
	"SkeletonLordMissing",
	"SkeletonLordDie",
	"SkeletonLordRecognize",
	"SkeletonLordHurt",
	"BomberRecognize",
	"BomberSummon",
	"BomberDie",
	"BomberMove",
	"DemonRecognize",
	"DemonTaunt",
	"DemonSpellInit",
	"DemonDie",
	"DemonMove",
	"DemonHurt",
	"GruntMove",
	"GruntTaunt",
	"GruntIdle",
	"GruntAttackInit",
	"GruntHitting",
	"GruntMissing",
	"GruntDie",
	"GruntBowTwang",
	"GruntRecognize",
	"GruntHurt",
	"OgreBruteListen",
	"OgreBruteTaunt",
	"OgreBruteIdle",
	"OgreBruteEngage",
	"OgreBruteRecognize",
	"OgreBruteMove",
	"OgreBruteHurt",
	"OgreBruteDie",
	"OgreBruteMeleeHit",
	"OgreBruteMeleeMiss",
	"OgreBruteAttackInit",
	"OgreWarlordListen",
	"OgreWarlordTaunt",
	"OgreWarlordIdle",
	"OgreWarlordEngage",
	"OgreWarlordRecognize",
	"OgreWarlordMove",
	"OgreWarlordHurt",
	"OgreWarlordDie",
	"OgreWarlordMeleeHit",
	"OgreWarlordMeleeMiss",
	"OgreWarlordAttackInit",
	"OgreWarlordThrow",
	"ScorpionRecognize",
	"ScorpionMove",
	"ScorpionIdle",
	"ScorpionAttackInit",
	"ScorpionStingHit",
	"ScorpionStingMiss",
	"ScorpionClawHit",
	"ScorpionClawMiss",
	"ScorpionHurt",
	"ScorpionDie",
	"LeechMove",
	"LeechIdle",
	"LeechAttackInit",
	"LeechHitting",
	"LeechMissing",
	"LeechDie",
	"LeechRecognize",
	"LeechHurt",
	"BearMove",
	"BearAttackInit",
	"BearHitting",
	"BearMissing",
	"BearDie",
	"BearRecognize",
	"BearHurt",
	"WolfMove",
	"WolfIdle",
	"WolfAttackInit",
	"WolfHitting",
	"WolfMissing",
	"WolfDie",
	"WolfRecognize",
	"WolfHurt",
	"WolfHowl",
	"WolfGrowl",
	"PlantSleep",
	"PlantAttackInit",
	"PlantHitting",
	"PlantMissing",
	"PlantDie",
	"PlantRecognize",
	"PlantHurt",
	"PlantGrowl",
	"MimicMove",
	"MimicIdle",
	"MimicAttackInit",
	"MimicHitting",
	"MimicMissing",
	"MimicDie",
	"MimicRecognize",
	"MimicHurt",
	"MimicMorph",
	"ZombieMove",
	"ZombieIdle",
	"ZombieAttackInit",
	"ZombieHitting",
	"ZombieMissing",
	"ZombieDie",
	"ZombieRecognize",
	"ZombieHurt",
	"ZombieGetUp",
	"VileZombieMove",
	"VileZombieIdle",
	"VileZombieAttackInit",
	"VileZombieHitting",
	"VileZombieMissing",
	"VileZombieDie",
	"VileZombieRecognize",
	"VileZombieHurt",
	"VileZombieGetUp",
	"ImpMove",
	"ImpShoot",
	"ImpSteal",
	"ImpDie",
	"ImpRecognize",
	"GolemMove",
	"GolemHitting",
	"GolemMissing",
	"GolemDie",
	"GolemHurt",
	"GolemRecognize",
	"MechGolemMove",
	"MechGolemAttackInit",
	"MechGolemHitting",
	"MechGolemMissing",
	"MechGolemDie",
	"MechGolemHurt",
	"MechGolemRecognize",
	"TowerRecognize",
	"TowerShoot",
	"SkullRecognize",
	"SkullShoot",
	"GhostMove",
	"GhostHitting",
	"GhostDie",
	"GhostHurt",
	"GhostRecognize",
	"WizardTalkable",
	"WizardMove",
	"WizardDie",
	"WizardHurt",
	"WizardRecognize",
	"WizardEngage",
	"WizardRetreat",
	"WaspMove",
	"WaspIdle",
	"WaspSting",
	"WaspDie",
	"WaspRecognize",
	"EmberDemonMove",
	"EmberDemonTaunt",
	"EmberDemonHitting",
	"EmberDemonMissing",
	"EmberDemonDie",
	"EmberDemonThrow",
	"EmberDemonRecognize",
	"EmberDemonHurt",
	"UrchinMove",
	"UrchinTaunt",
	"UrchinIdle",
	"UrchinDie",
	"UrchinThrow",
	"UrchinRecognize",
	"UrchinHurt",
	"UrchinFlee",
	"UrchinShamanMove",
	"UrchinShamanTaunt",
	"UrchinShamanIdle",
	"UrchinShamanDie",
	"UrchinShamanRecognize",
	"UrchinShamanHurt",
	"UrchinShamanFlee",
	"ArcherMove",
	"ArcherTaunt",
	"ArcherIdle",
	"ArcherDie",
	"ArcherMissileInit",
	"ArcherShoot",
	"ArcherRecognize",
	"ArcherHurt",
	"ArcherRetreat",
	"SwordsmanMove",
	"SwordsmanTaunt",
	"SwordsmanIdle",
	"SwordsmanAttackInit",
	"SwordsmanHitting",
	"SwordsmanMissing",
	"SwordsmanDie",
	"SwordsmanRecognize",
	"SwordsmanHurt",
	"SwordsmanRetreat",
	"BeholderMove",
	"BeholderIdle",
	"BeholderAttackInit",
	"BeholderDie",
	"BeholderRecognize",
	"BeholderHurt",
	"DryadMove",
	"DryadTaunt",
	"DryadDie",
	"DryadRecognize",
	"DryadHurt",
	"EvilCherubMove",
	"EvilCherubTaunt",
	"EvilCherubIdle",
	"EvilCherubMissileInit",
	"EvilCherubShoot",
	"EvilCherubDie",
	"EvilCherubRecognize",
	"EvilCherubHurt",
	"FishDie",
	"FrogDie",
	"FrogRecognize",
	"HecubahTaunt",
	"HecubahTalkable",
	"HecubahMove",
	"HecubahAttackInit",
	"HecubahDie",
	"HecubahRecognize",
	"HecubahHurt",
	"HecubahDieFrame0A",
	"HecubahDieFrame0B",
	"HecubahDieFrame98",
	"HecubahDieFrame194",
	"HecubahDieFrame283",
	"HecubahDieFrame439",
	"NecromancerTaunt",
	"NecromancerTalkable",
	"NecromancerMove",
	"NecromancerAttackInit",
	"NecromancerDie",
	"NecromancerRecognize",
	"NecromancerEngage",
	"NecromancerRetreat",
	"NecromancerHurt",
	"LichMove",
	"LichAttackInit",
	"LichDie",
	"LichRecognize",
	"LichHurt",
	"FlyingGolemMove",
	"FlyingGolemShoot",
	"FlyingGolemDie",
	"FlyingGolemRecognize",
	"FlyingGolemHurt",
	"NPCTalkable",
	"NPCIdle",
	"NPCDie",
	"NPCRecognize",
	"NPCRetreat",
	"NPCHurt",
	"MaidenIdle",
	"MaidenTalkable",
	"MaidenFlee",
	"MaidenDie",
	"MaidenHurt",
	"RatDie",
	"ShadeMove",
	"ShadeAttackInit",
	"ShadeDie",
	"ShadeRecognize",
	"ShadeHurt",
	"WeirdlingMove",
	"WillOWispMove",
	"WillOWispIdle",
	"WillOWispDie",
	"WillOWispHurt",
	"WillOWispRecognize",
	"WillOWispEngage",
	"TrollMove",
	"TrollIdle",
	"TrollDie",
	"TrollHurt",
	"TrollRecognize",
	"TrollAttackInit",
	"TrollFlatus",
	"MaleNPC1Talkable",
	"MaleNPC1Idle",
	"MaleNPC1Recognize",
	"MaleNPC1Engage",
	"MaleNPC1Retreat",
	"MaleNPC1Hurt",
	"MaleNPC1Die",
	"MaleNPC1AttackInit",
	"MaleNPC2Talkable",
	"MaleNPC2Idle",
	"MaleNPC2Recognize",
	"MaleNPC2Engage",
	"MaleNPC2Retreat",
	"MaleNPC2Hurt",
	"MaleNPC2Die",
	"MaleNPC2AttackInit",
	"Maiden1Talkable",
	"Maiden1Idle",
	"Maiden1Recognize",
	"Maiden1Retreat",
	"Maiden1Hurt",
	"Maiden1Die",
	"Maiden1AttackInit",
	"Maiden2Talkable",
	"Maiden2Idle",
	"Maiden2Recognize",
	"Maiden2Retreat",
	"Maiden2Hurt",
	"Maiden2Die",
	"Maiden2AttackInit",
	"HorvathTalkable",
	"HorvathEngage",
	"HorvathHurt",
	"HorvathDie",
	"Wizard1Talkable",
	"Wizard1Idle",
	"Wizard1Recognize",
	"Wizard1Engage",
	"Wizard1Retreat",
	"Wizard1Hurt",
	"Wizard1Die",
	"Wizard1AttackInit",
	"Wizard2Talkable",
	"Wizard2Idle",
	"Wizard2Recognize",
	"Wizard2Engage",
	"Wizard2Retreat",
	"Wizard2Hurt",
	"Wizard2Die",
	"Wizard2AttackInit",
	"FireKnight1Talkable",
	"FireKnight1Idle",
	"FireKnight1Recognize",
	"FireKnight1Engage",
	"FireKnight1Retreat",
	"FireKnight1Hurt",
	"FireKnight1Die",
	"FireKnight1AttackInit",
	"FireKnight2Talkable",
	"FireKnight2Idle",
	"FireKnight2Recognize",
	"FireKnight2Engage",
	"FireKnight2Retreat",
	"FireKnight2Hurt",
	"FireKnight2Die",
	"FireKnight2AttackInit",
	"Guard1Talkable",
	"Guard1Idle",
	"Guard1Recognize",
	"Guard1Engage",
	"Guard1Retreat",
	"Guard1Hurt",
	"Guard1Die",
	"Guard1AttackInit",
	"Guard2Talkable",
	"Guard2Idle",
	"Guard2Recognize",
	"Guard2Engage",
	"Guard2Retreat",
	"Guard2Hurt",
	"Guard2Die",
	"Guard2AttackInit",
	"WoundedNPCTalkable",
	"WoundedNPCIdle",
	"WoundedNPCRecognize",
	"WoundedNPCRetreat",
	"WoundedNPCHurt",
	"WoundedNPCDie",
	"WoundedNPCAttackInit",
	"HorrendousTalkable",
	"HorrendousRecognize",
	"HorrendousRetreat",
	"HorrendousHurt",
	"HorrendousDie",
	"HorrendousAttackInit",
	"SecretWallOpen",
	"SecretWallClose",
	"SecretWallEarthOpen",
	"SecretWallEarthClose",
	"SecretWallMetalOpen",
	"SecretWallMetalClose",
	"SecretWallStoneOpen",
	"SecretWallStoneClose",
	"SecretWallWoodOpen",
	"SecretWallWoodClose",
	"TriggerPressed",
	"TriggerReleased",
	"PotionUse",
	"PotionBreak",
	"RestoreHealth",
	"RestoreMana",
	"WallDestroyed",
	"WallDestroyedStone",
	"WallDestroyedWood",
	"WallDestroyedMetal",
	"ChestOpen",
	"CryptChestOpen",
	"SackChestOpen",
	"ChestLocked",
	"EggBreak",
	"Poisoned",
	"ButtonPress",
	"ButtonRelease",
	"LeverToggle",
	"SwitchToggle",
	"ChainPull",
	"ShortBellsUp",
	"LongBellsUp",
	"LongBellsDown",
	"BigBell",
	"MetallicBong",
	"Chime",
	"BigGong",
	"SmallGong",
	"MysticChant",
	"TripleChime",
	"Clank1",
	"Clank2",
	"Clank3",
	"MapOpen",
	"MapClose",
	"BookOpen",
	"BookClose",
	"PageTurn",
	"InventoryOpen",
	"InventoryClose",
	"InventoryPickup",
	"InventoryDrop",
	"SpellPickup",
	"SpellDrop",
	"SpellPopOffBook",
	"TrapEditorOpen",
	"TrapEditorClose",
	"ChangeSpellbar",
	"ExpandSpellbar",
	"CollapseSpellbar",
	"CreatureCageAppears",
	"CreatureCageHides",
	"ShopRepairItem",
	"MetalArmorPickup",
	"MetalArmorDrop",
	"MetalArmorBreak",
	"LeatherArmorPickup",
	"LeatherArmorDrop",
	"LeatherArmorBreak",
	"WoodenArmorPickup",
	"WoodenArmorDrop",
	"WoodenArmorBreak",
	"ClothArmorPickup",
	"ClothArmorDrop",
	"ClothArmorBreak",
	"ShoesPickup",
	"ShoesDrop",
	"MetalWeaponBreak",
	"WoodWeaponBreak",
	"KeyPickup",
	"KeyDrop",
	"AmuletPickup",
	"AmuletDrop",
	"TrapPickup",
	"TrapDrop",
	"BookPickup",
	"BookDrop",
	"ScrollPickup",
	"ScrollDrop",
	"WandPickup",
	"WandDrop",
	"PotionPickup",
	"PotionDrop",
	"MeatPickup",
	"MeatDrop",
	"ApplePickup",
	"AppleDrop",
	"ShroomPickup",
	"ShroomDrop",
	"SpectaclesPickup",
	"SpectaclesDrop",
	"MetalWeaponPickup",
	"MetalWeaponDrop",
	"WoodenWeaponPickup",
	"WoodenWeaponDrop",
	"BearTrapTriggered",
	"PoisonTrapTriggered",
	"StoneHitStone",
	"StoneHitEarth",
	"StoneHitWood",
	"StoneHitMetal",
	"StoneHitFlesh",
	"WoodHitStone",
	"WoodHitEarth",
	"WoodHitWood",
	"WoodHitMetal",
	"WoodHitFlesh",
	"MetalHitStone",
	"MetalHitEarth",
	"MetalHitWood",
	"MetalHitMetal",
	"MetalHitFlesh",
	"FleshHitStone",
	"FleshHitEarth",
	"FleshHitWood",
	"FleshHitMetal",
	"FleshHitFlesh",
	"DiamondHitStone",
	"DiamondHitEarth",
	"DiamondHitWood",
	"DiamondHitMetal",
	"DiamondHitFlesh",
	"HitStoneBreakable",
	"HitEarthBreakable",
	"HitWoodBreakable",
	"HitMetalBreakable",
	"HitMagicBreakable",
	"HitMetalShield",
	"PunchMissing",
	"LongswordMissing",
	"SwordMissing",
	"HammerMissing",
	"AxeMissing",
	"MaceMissing",
	"BowShoot",
	"CrossBowShoot",
	"BowEmpty",
	"CrossBowEmpty",
	"ArrowTrapShoot",
	"GreatSwordReflect",
	"ChakramThrow",
	"ChakramCatch",
	"ChakramFallToGround",
	"StaffBlock",
	"NextWeapon",
	"HeartBeat",
	"GenerateTick",
	"SummonClick",
	"SummonComplete",
	"SummonAbort",
	"ManaClick",
	"LevelUp",
	"JournalEntryAdd",
	"SecretFound",
	"EarthRumbleMajor",
	"EarthRumbleMinor",
	"ElectricalArc1",
	"FloorSpikesUp",
	"FloorSpikesDown",
	"SpikeBlockMove",
	"BoulderRoll",
	"ArcheryContestBegins",
	"HorrendousIsKilled",
	"StaffOblivionAchieve1",
	"StaffOblivionAchieve2",
	"StaffOblivionAchieve3",
	"StaffOblivionAchieve4",
	"FireGrate",
	"MechGolemPowerUp",
	"ShellSelect",
	"ShellClick",
	"ShellSlideIn",
	"ShellSlideOut",
	"ShellMouseBoom",
	"NoCanDo",
	"BallThrow",
	"BallGrab",
	"BallBounce",
	"BallHitGoal",
	"BirdAmbient1",
	"LoopAmbienceCastle",
	"LoopAmbienceCave",
	"LoopAmbienceForest",
	"LoopAmbienceInferno",
	"LoopAmbienceLOTD",
	"LoopAmbienceMine",
	"LoopAmbienceSwamp",
	"LoopAmbBird2",
	"LoopAmbBirdSwamp1",
	"LoopAmbBirdSwamp2",
	"LoopAmbBrook2",
	"LoopAmbBrook3",
	"LoopAmbCricket1",
	"LoopAmbCricket2",
	"LoopAmbCricket3",
	"LoopAmbCrow1",
	"LoopAmbCrow2",
	"LoopAmbCrowWL",
	"LoopAmbDog1",
	"LoopAmbDripCave1",
	"LoopAmbDripCave2",
	"LoopAmbDripRoom",
	"LoopAmbFrogSwamp1",
	"LoopAmbFrogSwamp2",
	"LoopAmbFrogSwamp3",
	"LoopAmbFrogSwamp4",
	"LoopAmbFrogSwamp5",
	"LoopAmbFliesSwamp",
	"LoopAmbRodentForest1",
	"LoopAmbRodentForest2",
	"LoopAmbCaveRumble",
	"LoopAmbSpiritsFOV",
	"LoopAmbSpiritsLOTD",
	"LoopAmbWindCave1",
	"LoopAmbWindCave2",
	"LoopAmbWindCave3",
	"LoopAmbWindLOTD",
	"LoopAmbWindWL1",
	"LoopAmbWindWL2",
	"LoopAmbHeartNox",
	"LoopAmbBird3",
	"LoopAmbBird4",
	"LoopAmbBird5",
	"LoopAmbBird6",
	"LoopAmbBird7",
	"LoopAmbBird8",
	"LoopAmbIxTemple",
	"LoopAmbLeaves",
	"LoopAmbHowls",
	"LoopAmbWeirdling",
	"LoopAmbSpikeWave",
	"LoopAmbBeachBirds",
	"LoopAmbBeachWaves",
	"LoopCampfire",
	"LoopTorch",
	"LoopBlueFire",
	"LoopWorkstation",
	"LoopWaterFountain",
	"LoopWindmill",
	"LoopOrrery",
	"LoopVandegraf",
	"LoopGearSmall",
	"LoopGearLarge",
	"LoopGearPulley",
	"LoopPolyp",
	"LoopSentryGlobe",
	"LoopSpikePillar",
	"HarpoonBroken",
	"HarpoonReel",
	"MonsterGeneratorDie",
	"MonsterGeneratorHurt",
	"MonsterGeneratorSpawn",
	"PlayerExit",
	"AwardLife",
	"SoulGateTouch",
	"QuestRespawn",
	"QuestFinalDeath",
	"QuestPlayerJoinGame",
	"QuestStatScreen",
	"QuestIntroScreen",
	"QuestPlayerExitGame",
	"QuestLockedChest",
	"LoopMonsterGenerator",
	"StoneDoorOpen",
	"StoneDoorClose",
	"DiamondDrop",
	"DiamondPickup",
	"RubyDrop",
	"RubyPickup",
	"EmeraldDrop",
	"EmeraldPickup",
	"EnableSharedKeyMode",
}
