package keybind

var defBindEvents = []BindEvent{
	{Name: "", Key: 0}, // represents no binding
	{Name: "MoveForward", Key: 0x2},
	{Name: "Action", Key: 0x1},
	{Name: "Jump", Key: 0x6},
	{Name: "ToggleInventory", Key: 0x7},
	{Name: "ToggleBook", Key: 0xa},
	{Name: "ToggleMap", Key: 0x10},
	{Name: "MapZoomOut", Key: 0x22},
	{Name: "MapZoomIn", Key: 0x21},
	{Name: "InvokeSlot1", Key: 0x1c},
	{Name: "InvokeSlot2", Key: 0x1d},
	{Name: "InvokeSlot3", Key: 0x1e},
	{Name: "InvokeSlot4", Key: 0x1f},
	{Name: "InvokeSlot5", Key: 0x20},
	{Name: "PreviousSpellSet", Key: 0x28},
	{Name: "NextSpellSet", Key: 0x27},
	{Name: "SelectSpellSet", Key: 0x29},
	{Name: "InvertSpellTarget", Key: 0x31},
	{Name: "PlaceTrapBomber", Key: 0x2a},
	{Name: "SwapWeapons", Key: 0x23},
	{Name: "QuickHealth", Key: 0x24},
	{Name: "QuickMana", Key: 0x25},
	{Name: "QuickCurePoison", Key: 0x26},
	{Name: "Chat", Key: 0x8},
	{Name: "TeamChat", Key: 0x9},
	{Name: "ToggleConsole", Key: 0xb},
	{Name: "ToggleQuitMenu", Key: 0x2c},
	{Name: "ToggleServerMenu", Key: 0x2d},
	{Name: "ToggleRank", Key: 0x32},
	{Name: "ToggleNetstat", Key: 0x33},
	{Name: "ToggleGUI", Key: 0x34},
	{Name: "AutoSave", Key: 0x35},
	{Name: "AutoLoad", Key: 0x36},
	{Name: "Taunt", Key: 0x2e},
	{Name: "Point", Key: 0x30},
	{Name: "Laugh", Key: 0x2f},
	{Name: "IncreaseWindowSize", Key: 0xc},
	{Name: "DecreaseWindowSize", Key: 0xd},
	{Name: "IncreaseGamma", Key: 0xe},
	{Name: "DecreaseGamma", Key: 0xf},
	{Name: "ScreenShot", Key: 0x37},
}
