package keybind

var defBindEvents = []BindEvent{
	{Name: "", Event: 0}, // represents no binding
	{Name: "MoveForward", Event: 0x2},
	{Name: "Action", Event: 0x1},
	{Name: "Jump", Event: 0x6},
	{Name: "ToggleInventory", Event: 0x7},
	{Name: "ToggleBook", Event: 0xa},
	{Name: "ToggleMap", Event: 0x10},
	{Name: "MapZoomOut", Event: 0x22},
	{Name: "MapZoomIn", Event: 0x21},
	{Name: "InvokeSlot1", Event: 0x1c},
	{Name: "InvokeSlot2", Event: 0x1d},
	{Name: "InvokeSlot3", Event: 0x1e},
	{Name: "InvokeSlot4", Event: 0x1f},
	{Name: "InvokeSlot5", Event: 0x20},
	{Name: "PreviousSpellSet", Event: 0x28},
	{Name: "NextSpellSet", Event: 0x27},
	{Name: "SelectSpellSet", Event: 0x29},
	{Name: "InvertSpellTarget", Event: 0x31},
	{Name: "PlaceTrapBomber", Event: 0x2a},
	{Name: "SwapWeapons", Event: 0x23},
	{Name: "QuickHealth", Event: 0x24},
	{Name: "QuickMana", Event: 0x25},
	{Name: "QuickCurePoison", Event: 0x26},
	{Name: "Chat", Event: 0x8},
	{Name: "TeamChat", Event: 0x9},
	{Name: "ToggleConsole", Event: 0xb},
	{Name: "ToggleQuitMenu", Event: 0x2c},
	{Name: "ToggleServerMenu", Event: 0x2d},
	{Name: "ToggleRank", Event: 0x32},
	{Name: "ToggleNetstat", Event: 0x33},
	{Name: "ToggleGUI", Event: 0x34},
	{Name: "AutoSave", Event: 0x35},
	{Name: "AutoLoad", Event: 0x36},
	{Name: "Taunt", Event: 0x2e},
	{Name: "Point", Event: 0x30},
	{Name: "Laugh", Event: 0x2f},
	{Name: "IncreaseWindowSize", Event: 0xc},
	{Name: "DecreaseWindowSize", Event: 0xd},
	{Name: "IncreaseGamma", Event: 0xe},
	{Name: "DecreaseGamma", Event: 0xf},
	{Name: "ScreenShot", Event: 0x37},
}
