// Code generated by callgen; DO NOT EDIT.

package ccall

/*
#include <stdint.h>

static void go_call_void_void_func(void (*fnc)(void)) { fnc(); }
static void go_call_void_uptr_func(void (*fnc)(uintptr_t), uintptr_t a1) { fnc(a1); }
static void go_call_void_uptr2_func(void (*fnc)(uintptr_t, uintptr_t), uintptr_t a1, uintptr_t a2) { fnc(a1, a2); }
static void go_call_void_uptr3_func(void (*fnc)(uintptr_t, uintptr_t, uintptr_t), uintptr_t a1, uintptr_t a2, uintptr_t a3) { fnc(a1, a2, a3); }
static void go_call_void_uptr4_func(void (*fnc)(uintptr_t, uintptr_t, uintptr_t, uintptr_t), uintptr_t a1, uintptr_t a2, uintptr_t a3, uintptr_t a4) { fnc(a1, a2, a3, a4); }
static void go_call_void_uptr5_func(void (*fnc)(uintptr_t, uintptr_t, uintptr_t, uintptr_t, uintptr_t), uintptr_t a1, uintptr_t a2, uintptr_t a3, uintptr_t a4, uintptr_t a5) { fnc(a1, a2, a3, a4, a5); }
static void go_call_void_uptr6_func(void (*fnc)(uintptr_t, uintptr_t, uintptr_t, uintptr_t, uintptr_t, uintptr_t), uintptr_t a1, uintptr_t a2, uintptr_t a3, uintptr_t a4, uintptr_t a5, uintptr_t a6) { fnc(a1, a2, a3, a4, a5, a6); }
static void go_call_void_ptr_func(void (*fnc)(void*), void* a1) { fnc(a1); }
static void go_call_void_ptr2_func(void (*fnc)(void*, void*), void* a1, void* a2) { fnc(a1, a2); }
static void go_call_void_ptr3_func(void (*fnc)(void*, void*, void*), void* a1, void* a2, void* a3) { fnc(a1, a2, a3); }
static void go_call_void_ptr4_func(void (*fnc)(void*, void*, void*, void*), void* a1, void* a2, void* a3, void* a4) { fnc(a1, a2, a3, a4); }
static void go_call_void_ptr5_func(void (*fnc)(void*, void*, void*, void*, void*), void* a1, void* a2, void* a3, void* a4, void* a5) { fnc(a1, a2, a3, a4, a5); }
static void go_call_void_ptr6_func(void (*fnc)(void*, void*, void*, void*, void*, void*), void* a1, void* a2, void* a3, void* a4, void* a5, void* a6) { fnc(a1, a2, a3, a4, a5, a6); }
static void go_call_void_int_func(void (*fnc)(int), int a1) { fnc(a1); }
static void go_call_void_int2_func(void (*fnc)(int, int), int a1, int a2) { fnc(a1, a2); }
static void go_call_void_int3_func(void (*fnc)(int, int, int), int a1, int a2, int a3) { fnc(a1, a2, a3); }
static void go_call_void_int4_func(void (*fnc)(int, int, int, int), int a1, int a2, int a3, int a4) { fnc(a1, a2, a3, a4); }
static void go_call_void_int5_func(void (*fnc)(int, int, int, int, int), int a1, int a2, int a3, int a4, int a5) { fnc(a1, a2, a3, a4, a5); }
static void go_call_void_int6_func(void (*fnc)(int, int, int, int, int, int), int a1, int a2, int a3, int a4, int a5, int a6) { fnc(a1, a2, a3, a4, a5, a6); }
static uintptr_t go_call_uptr_void_func(uintptr_t (*fnc)(void)) { return fnc(); }
static uintptr_t go_call_uptr_uptr_func(uintptr_t (*fnc)(uintptr_t), uintptr_t a1) { return fnc(a1); }
static uintptr_t go_call_uptr_uptr2_func(uintptr_t (*fnc)(uintptr_t, uintptr_t), uintptr_t a1, uintptr_t a2) { return fnc(a1, a2); }
static uintptr_t go_call_uptr_uptr3_func(uintptr_t (*fnc)(uintptr_t, uintptr_t, uintptr_t), uintptr_t a1, uintptr_t a2, uintptr_t a3) { return fnc(a1, a2, a3); }
static uintptr_t go_call_uptr_uptr4_func(uintptr_t (*fnc)(uintptr_t, uintptr_t, uintptr_t, uintptr_t), uintptr_t a1, uintptr_t a2, uintptr_t a3, uintptr_t a4) { return fnc(a1, a2, a3, a4); }
static uintptr_t go_call_uptr_uptr5_func(uintptr_t (*fnc)(uintptr_t, uintptr_t, uintptr_t, uintptr_t, uintptr_t), uintptr_t a1, uintptr_t a2, uintptr_t a3, uintptr_t a4, uintptr_t a5) { return fnc(a1, a2, a3, a4, a5); }
static uintptr_t go_call_uptr_uptr6_func(uintptr_t (*fnc)(uintptr_t, uintptr_t, uintptr_t, uintptr_t, uintptr_t, uintptr_t), uintptr_t a1, uintptr_t a2, uintptr_t a3, uintptr_t a4, uintptr_t a5, uintptr_t a6) { return fnc(a1, a2, a3, a4, a5, a6); }
static uintptr_t go_call_uptr_ptr_func(uintptr_t (*fnc)(void*), void* a1) { return fnc(a1); }
static uintptr_t go_call_uptr_ptr2_func(uintptr_t (*fnc)(void*, void*), void* a1, void* a2) { return fnc(a1, a2); }
static uintptr_t go_call_uptr_ptr3_func(uintptr_t (*fnc)(void*, void*, void*), void* a1, void* a2, void* a3) { return fnc(a1, a2, a3); }
static uintptr_t go_call_uptr_ptr4_func(uintptr_t (*fnc)(void*, void*, void*, void*), void* a1, void* a2, void* a3, void* a4) { return fnc(a1, a2, a3, a4); }
static uintptr_t go_call_uptr_ptr5_func(uintptr_t (*fnc)(void*, void*, void*, void*, void*), void* a1, void* a2, void* a3, void* a4, void* a5) { return fnc(a1, a2, a3, a4, a5); }
static uintptr_t go_call_uptr_ptr6_func(uintptr_t (*fnc)(void*, void*, void*, void*, void*, void*), void* a1, void* a2, void* a3, void* a4, void* a5, void* a6) { return fnc(a1, a2, a3, a4, a5, a6); }
static uintptr_t go_call_uptr_int_func(uintptr_t (*fnc)(int), int a1) { return fnc(a1); }
static uintptr_t go_call_uptr_int2_func(uintptr_t (*fnc)(int, int), int a1, int a2) { return fnc(a1, a2); }
static uintptr_t go_call_uptr_int3_func(uintptr_t (*fnc)(int, int, int), int a1, int a2, int a3) { return fnc(a1, a2, a3); }
static uintptr_t go_call_uptr_int4_func(uintptr_t (*fnc)(int, int, int, int), int a1, int a2, int a3, int a4) { return fnc(a1, a2, a3, a4); }
static uintptr_t go_call_uptr_int5_func(uintptr_t (*fnc)(int, int, int, int, int), int a1, int a2, int a3, int a4, int a5) { return fnc(a1, a2, a3, a4, a5); }
static uintptr_t go_call_uptr_int6_func(uintptr_t (*fnc)(int, int, int, int, int, int), int a1, int a2, int a3, int a4, int a5, int a6) { return fnc(a1, a2, a3, a4, a5, a6); }
static void* go_call_ptr_void_func(void* (*fnc)(void)) { return fnc(); }
static void* go_call_ptr_uptr_func(void* (*fnc)(uintptr_t), uintptr_t a1) { return fnc(a1); }
static void* go_call_ptr_uptr2_func(void* (*fnc)(uintptr_t, uintptr_t), uintptr_t a1, uintptr_t a2) { return fnc(a1, a2); }
static void* go_call_ptr_uptr3_func(void* (*fnc)(uintptr_t, uintptr_t, uintptr_t), uintptr_t a1, uintptr_t a2, uintptr_t a3) { return fnc(a1, a2, a3); }
static void* go_call_ptr_uptr4_func(void* (*fnc)(uintptr_t, uintptr_t, uintptr_t, uintptr_t), uintptr_t a1, uintptr_t a2, uintptr_t a3, uintptr_t a4) { return fnc(a1, a2, a3, a4); }
static void* go_call_ptr_uptr5_func(void* (*fnc)(uintptr_t, uintptr_t, uintptr_t, uintptr_t, uintptr_t), uintptr_t a1, uintptr_t a2, uintptr_t a3, uintptr_t a4, uintptr_t a5) { return fnc(a1, a2, a3, a4, a5); }
static void* go_call_ptr_uptr6_func(void* (*fnc)(uintptr_t, uintptr_t, uintptr_t, uintptr_t, uintptr_t, uintptr_t), uintptr_t a1, uintptr_t a2, uintptr_t a3, uintptr_t a4, uintptr_t a5, uintptr_t a6) { return fnc(a1, a2, a3, a4, a5, a6); }
static void* go_call_ptr_ptr_func(void* (*fnc)(void*), void* a1) { return fnc(a1); }
static void* go_call_ptr_ptr2_func(void* (*fnc)(void*, void*), void* a1, void* a2) { return fnc(a1, a2); }
static void* go_call_ptr_ptr3_func(void* (*fnc)(void*, void*, void*), void* a1, void* a2, void* a3) { return fnc(a1, a2, a3); }
static void* go_call_ptr_ptr4_func(void* (*fnc)(void*, void*, void*, void*), void* a1, void* a2, void* a3, void* a4) { return fnc(a1, a2, a3, a4); }
static void* go_call_ptr_ptr5_func(void* (*fnc)(void*, void*, void*, void*, void*), void* a1, void* a2, void* a3, void* a4, void* a5) { return fnc(a1, a2, a3, a4, a5); }
static void* go_call_ptr_ptr6_func(void* (*fnc)(void*, void*, void*, void*, void*, void*), void* a1, void* a2, void* a3, void* a4, void* a5, void* a6) { return fnc(a1, a2, a3, a4, a5, a6); }
static void* go_call_ptr_int_func(void* (*fnc)(int), int a1) { return fnc(a1); }
static void* go_call_ptr_int2_func(void* (*fnc)(int, int), int a1, int a2) { return fnc(a1, a2); }
static void* go_call_ptr_int3_func(void* (*fnc)(int, int, int), int a1, int a2, int a3) { return fnc(a1, a2, a3); }
static void* go_call_ptr_int4_func(void* (*fnc)(int, int, int, int), int a1, int a2, int a3, int a4) { return fnc(a1, a2, a3, a4); }
static void* go_call_ptr_int5_func(void* (*fnc)(int, int, int, int, int), int a1, int a2, int a3, int a4, int a5) { return fnc(a1, a2, a3, a4, a5); }
static void* go_call_ptr_int6_func(void* (*fnc)(int, int, int, int, int, int), int a1, int a2, int a3, int a4, int a5, int a6) { return fnc(a1, a2, a3, a4, a5, a6); }
static int go_call_int_void_func(int (*fnc)(void)) { return fnc(); }
static int go_call_int_uptr_func(int (*fnc)(uintptr_t), uintptr_t a1) { return fnc(a1); }
static int go_call_int_uptr2_func(int (*fnc)(uintptr_t, uintptr_t), uintptr_t a1, uintptr_t a2) { return fnc(a1, a2); }
static int go_call_int_uptr3_func(int (*fnc)(uintptr_t, uintptr_t, uintptr_t), uintptr_t a1, uintptr_t a2, uintptr_t a3) { return fnc(a1, a2, a3); }
static int go_call_int_uptr4_func(int (*fnc)(uintptr_t, uintptr_t, uintptr_t, uintptr_t), uintptr_t a1, uintptr_t a2, uintptr_t a3, uintptr_t a4) { return fnc(a1, a2, a3, a4); }
static int go_call_int_uptr5_func(int (*fnc)(uintptr_t, uintptr_t, uintptr_t, uintptr_t, uintptr_t), uintptr_t a1, uintptr_t a2, uintptr_t a3, uintptr_t a4, uintptr_t a5) { return fnc(a1, a2, a3, a4, a5); }
static int go_call_int_uptr6_func(int (*fnc)(uintptr_t, uintptr_t, uintptr_t, uintptr_t, uintptr_t, uintptr_t), uintptr_t a1, uintptr_t a2, uintptr_t a3, uintptr_t a4, uintptr_t a5, uintptr_t a6) { return fnc(a1, a2, a3, a4, a5, a6); }
static int go_call_int_ptr_func(int (*fnc)(void*), void* a1) { return fnc(a1); }
static int go_call_int_ptr2_func(int (*fnc)(void*, void*), void* a1, void* a2) { return fnc(a1, a2); }
static int go_call_int_ptr3_func(int (*fnc)(void*, void*, void*), void* a1, void* a2, void* a3) { return fnc(a1, a2, a3); }
static int go_call_int_ptr4_func(int (*fnc)(void*, void*, void*, void*), void* a1, void* a2, void* a3, void* a4) { return fnc(a1, a2, a3, a4); }
static int go_call_int_ptr5_func(int (*fnc)(void*, void*, void*, void*, void*), void* a1, void* a2, void* a3, void* a4, void* a5) { return fnc(a1, a2, a3, a4, a5); }
static int go_call_int_ptr6_func(int (*fnc)(void*, void*, void*, void*, void*, void*), void* a1, void* a2, void* a3, void* a4, void* a5, void* a6) { return fnc(a1, a2, a3, a4, a5, a6); }
static int go_call_int_int_func(int (*fnc)(int), int a1) { return fnc(a1); }
static int go_call_int_int2_func(int (*fnc)(int, int), int a1, int a2) { return fnc(a1, a2); }
static int go_call_int_int3_func(int (*fnc)(int, int, int), int a1, int a2, int a3) { return fnc(a1, a2, a3); }
static int go_call_int_int4_func(int (*fnc)(int, int, int, int), int a1, int a2, int a3, int a4) { return fnc(a1, a2, a3, a4); }
static int go_call_int_int5_func(int (*fnc)(int, int, int, int, int), int a1, int a2, int a3, int a4, int a5) { return fnc(a1, a2, a3, a4, a5); }
static int go_call_int_int6_func(int (*fnc)(int, int, int, int, int, int), int a1, int a2, int a3, int a4, int a5, int a6) { return fnc(a1, a2, a3, a4, a5, a6); }

*/
import "C"
import "unsafe"

func CallVoidVoid(fnc unsafe.Pointer) {
	C.go_call_void_void_func((*[0]byte)(fnc))
}

func CallVoidUPtr(fnc unsafe.Pointer, a1 uintptr) {
	C.go_call_void_uptr_func((*[0]byte)(fnc), C.uintptr_t(a1))
}

func CallVoidUPtr2(fnc unsafe.Pointer, a1 uintptr, a2 uintptr) {
	C.go_call_void_uptr2_func((*[0]byte)(fnc), C.uintptr_t(a1), C.uintptr_t(a2))
}

func CallVoidUPtr3(fnc unsafe.Pointer, a1 uintptr, a2 uintptr, a3 uintptr) {
	C.go_call_void_uptr3_func((*[0]byte)(fnc), C.uintptr_t(a1), C.uintptr_t(a2), C.uintptr_t(a3))
}

func CallVoidUPtr4(fnc unsafe.Pointer, a1 uintptr, a2 uintptr, a3 uintptr, a4 uintptr) {
	C.go_call_void_uptr4_func((*[0]byte)(fnc), C.uintptr_t(a1), C.uintptr_t(a2), C.uintptr_t(a3), C.uintptr_t(a4))
}

func CallVoidUPtr5(fnc unsafe.Pointer, a1 uintptr, a2 uintptr, a3 uintptr, a4 uintptr, a5 uintptr) {
	C.go_call_void_uptr5_func((*[0]byte)(fnc), C.uintptr_t(a1), C.uintptr_t(a2), C.uintptr_t(a3), C.uintptr_t(a4), C.uintptr_t(a5))
}

func CallVoidUPtr6(fnc unsafe.Pointer, a1 uintptr, a2 uintptr, a3 uintptr, a4 uintptr, a5 uintptr, a6 uintptr) {
	C.go_call_void_uptr6_func((*[0]byte)(fnc), C.uintptr_t(a1), C.uintptr_t(a2), C.uintptr_t(a3), C.uintptr_t(a4), C.uintptr_t(a5), C.uintptr_t(a6))
}

func CallVoidPtr(fnc unsafe.Pointer, a1 unsafe.Pointer) {
	C.go_call_void_ptr_func((*[0]byte)(fnc), a1)
}

func CallVoidPtr2(fnc unsafe.Pointer, a1 unsafe.Pointer, a2 unsafe.Pointer) {
	C.go_call_void_ptr2_func((*[0]byte)(fnc), a1, a2)
}

func CallVoidPtr3(fnc unsafe.Pointer, a1 unsafe.Pointer, a2 unsafe.Pointer, a3 unsafe.Pointer) {
	C.go_call_void_ptr3_func((*[0]byte)(fnc), a1, a2, a3)
}

func CallVoidPtr4(fnc unsafe.Pointer, a1 unsafe.Pointer, a2 unsafe.Pointer, a3 unsafe.Pointer, a4 unsafe.Pointer) {
	C.go_call_void_ptr4_func((*[0]byte)(fnc), a1, a2, a3, a4)
}

func CallVoidPtr5(fnc unsafe.Pointer, a1 unsafe.Pointer, a2 unsafe.Pointer, a3 unsafe.Pointer, a4 unsafe.Pointer, a5 unsafe.Pointer) {
	C.go_call_void_ptr5_func((*[0]byte)(fnc), a1, a2, a3, a4, a5)
}

func CallVoidPtr6(fnc unsafe.Pointer, a1 unsafe.Pointer, a2 unsafe.Pointer, a3 unsafe.Pointer, a4 unsafe.Pointer, a5 unsafe.Pointer, a6 unsafe.Pointer) {
	C.go_call_void_ptr6_func((*[0]byte)(fnc), a1, a2, a3, a4, a5, a6)
}

func CallVoidInt(fnc unsafe.Pointer, a1 int) {
	C.go_call_void_int_func((*[0]byte)(fnc), C.int(a1))
}

func CallVoidInt2(fnc unsafe.Pointer, a1 int, a2 int) {
	C.go_call_void_int2_func((*[0]byte)(fnc), C.int(a1), C.int(a2))
}

func CallVoidInt3(fnc unsafe.Pointer, a1 int, a2 int, a3 int) {
	C.go_call_void_int3_func((*[0]byte)(fnc), C.int(a1), C.int(a2), C.int(a3))
}

func CallVoidInt4(fnc unsafe.Pointer, a1 int, a2 int, a3 int, a4 int) {
	C.go_call_void_int4_func((*[0]byte)(fnc), C.int(a1), C.int(a2), C.int(a3), C.int(a4))
}

func CallVoidInt5(fnc unsafe.Pointer, a1 int, a2 int, a3 int, a4 int, a5 int) {
	C.go_call_void_int5_func((*[0]byte)(fnc), C.int(a1), C.int(a2), C.int(a3), C.int(a4), C.int(a5))
}

func CallVoidInt6(fnc unsafe.Pointer, a1 int, a2 int, a3 int, a4 int, a5 int, a6 int) {
	C.go_call_void_int6_func((*[0]byte)(fnc), C.int(a1), C.int(a2), C.int(a3), C.int(a4), C.int(a5), C.int(a6))
}

func CallUPtrVoid(fnc unsafe.Pointer) uintptr {
	return uintptr(C.go_call_uptr_void_func((*[0]byte)(fnc)))
}

func CallUPtrUPtr(fnc unsafe.Pointer, a1 uintptr) uintptr {
	return uintptr(C.go_call_uptr_uptr_func((*[0]byte)(fnc), C.uintptr_t(a1)))
}

func CallUPtrUPtr2(fnc unsafe.Pointer, a1 uintptr, a2 uintptr) uintptr {
	return uintptr(C.go_call_uptr_uptr2_func((*[0]byte)(fnc), C.uintptr_t(a1), C.uintptr_t(a2)))
}

func CallUPtrUPtr3(fnc unsafe.Pointer, a1 uintptr, a2 uintptr, a3 uintptr) uintptr {
	return uintptr(C.go_call_uptr_uptr3_func((*[0]byte)(fnc), C.uintptr_t(a1), C.uintptr_t(a2), C.uintptr_t(a3)))
}

func CallUPtrUPtr4(fnc unsafe.Pointer, a1 uintptr, a2 uintptr, a3 uintptr, a4 uintptr) uintptr {
	return uintptr(C.go_call_uptr_uptr4_func((*[0]byte)(fnc), C.uintptr_t(a1), C.uintptr_t(a2), C.uintptr_t(a3), C.uintptr_t(a4)))
}

func CallUPtrUPtr5(fnc unsafe.Pointer, a1 uintptr, a2 uintptr, a3 uintptr, a4 uintptr, a5 uintptr) uintptr {
	return uintptr(C.go_call_uptr_uptr5_func((*[0]byte)(fnc), C.uintptr_t(a1), C.uintptr_t(a2), C.uintptr_t(a3), C.uintptr_t(a4), C.uintptr_t(a5)))
}

func CallUPtrUPtr6(fnc unsafe.Pointer, a1 uintptr, a2 uintptr, a3 uintptr, a4 uintptr, a5 uintptr, a6 uintptr) uintptr {
	return uintptr(C.go_call_uptr_uptr6_func((*[0]byte)(fnc), C.uintptr_t(a1), C.uintptr_t(a2), C.uintptr_t(a3), C.uintptr_t(a4), C.uintptr_t(a5), C.uintptr_t(a6)))
}

func CallUPtrPtr(fnc unsafe.Pointer, a1 unsafe.Pointer) uintptr {
	return uintptr(C.go_call_uptr_ptr_func((*[0]byte)(fnc), a1))
}

func CallUPtrPtr2(fnc unsafe.Pointer, a1 unsafe.Pointer, a2 unsafe.Pointer) uintptr {
	return uintptr(C.go_call_uptr_ptr2_func((*[0]byte)(fnc), a1, a2))
}

func CallUPtrPtr3(fnc unsafe.Pointer, a1 unsafe.Pointer, a2 unsafe.Pointer, a3 unsafe.Pointer) uintptr {
	return uintptr(C.go_call_uptr_ptr3_func((*[0]byte)(fnc), a1, a2, a3))
}

func CallUPtrPtr4(fnc unsafe.Pointer, a1 unsafe.Pointer, a2 unsafe.Pointer, a3 unsafe.Pointer, a4 unsafe.Pointer) uintptr {
	return uintptr(C.go_call_uptr_ptr4_func((*[0]byte)(fnc), a1, a2, a3, a4))
}

func CallUPtrPtr5(fnc unsafe.Pointer, a1 unsafe.Pointer, a2 unsafe.Pointer, a3 unsafe.Pointer, a4 unsafe.Pointer, a5 unsafe.Pointer) uintptr {
	return uintptr(C.go_call_uptr_ptr5_func((*[0]byte)(fnc), a1, a2, a3, a4, a5))
}

func CallUPtrPtr6(fnc unsafe.Pointer, a1 unsafe.Pointer, a2 unsafe.Pointer, a3 unsafe.Pointer, a4 unsafe.Pointer, a5 unsafe.Pointer, a6 unsafe.Pointer) uintptr {
	return uintptr(C.go_call_uptr_ptr6_func((*[0]byte)(fnc), a1, a2, a3, a4, a5, a6))
}

func CallUPtrInt(fnc unsafe.Pointer, a1 int) uintptr {
	return uintptr(C.go_call_uptr_int_func((*[0]byte)(fnc), C.int(a1)))
}

func CallUPtrInt2(fnc unsafe.Pointer, a1 int, a2 int) uintptr {
	return uintptr(C.go_call_uptr_int2_func((*[0]byte)(fnc), C.int(a1), C.int(a2)))
}

func CallUPtrInt3(fnc unsafe.Pointer, a1 int, a2 int, a3 int) uintptr {
	return uintptr(C.go_call_uptr_int3_func((*[0]byte)(fnc), C.int(a1), C.int(a2), C.int(a3)))
}

func CallUPtrInt4(fnc unsafe.Pointer, a1 int, a2 int, a3 int, a4 int) uintptr {
	return uintptr(C.go_call_uptr_int4_func((*[0]byte)(fnc), C.int(a1), C.int(a2), C.int(a3), C.int(a4)))
}

func CallUPtrInt5(fnc unsafe.Pointer, a1 int, a2 int, a3 int, a4 int, a5 int) uintptr {
	return uintptr(C.go_call_uptr_int5_func((*[0]byte)(fnc), C.int(a1), C.int(a2), C.int(a3), C.int(a4), C.int(a5)))
}

func CallUPtrInt6(fnc unsafe.Pointer, a1 int, a2 int, a3 int, a4 int, a5 int, a6 int) uintptr {
	return uintptr(C.go_call_uptr_int6_func((*[0]byte)(fnc), C.int(a1), C.int(a2), C.int(a3), C.int(a4), C.int(a5), C.int(a6)))
}

func CallPtrVoid(fnc unsafe.Pointer) unsafe.Pointer {
	return C.go_call_ptr_void_func((*[0]byte)(fnc))
}

func CallPtrUPtr(fnc unsafe.Pointer, a1 uintptr) unsafe.Pointer {
	return C.go_call_ptr_uptr_func((*[0]byte)(fnc), C.uintptr_t(a1))
}

func CallPtrUPtr2(fnc unsafe.Pointer, a1 uintptr, a2 uintptr) unsafe.Pointer {
	return C.go_call_ptr_uptr2_func((*[0]byte)(fnc), C.uintptr_t(a1), C.uintptr_t(a2))
}

func CallPtrUPtr3(fnc unsafe.Pointer, a1 uintptr, a2 uintptr, a3 uintptr) unsafe.Pointer {
	return C.go_call_ptr_uptr3_func((*[0]byte)(fnc), C.uintptr_t(a1), C.uintptr_t(a2), C.uintptr_t(a3))
}

func CallPtrUPtr4(fnc unsafe.Pointer, a1 uintptr, a2 uintptr, a3 uintptr, a4 uintptr) unsafe.Pointer {
	return C.go_call_ptr_uptr4_func((*[0]byte)(fnc), C.uintptr_t(a1), C.uintptr_t(a2), C.uintptr_t(a3), C.uintptr_t(a4))
}

func CallPtrUPtr5(fnc unsafe.Pointer, a1 uintptr, a2 uintptr, a3 uintptr, a4 uintptr, a5 uintptr) unsafe.Pointer {
	return C.go_call_ptr_uptr5_func((*[0]byte)(fnc), C.uintptr_t(a1), C.uintptr_t(a2), C.uintptr_t(a3), C.uintptr_t(a4), C.uintptr_t(a5))
}

func CallPtrUPtr6(fnc unsafe.Pointer, a1 uintptr, a2 uintptr, a3 uintptr, a4 uintptr, a5 uintptr, a6 uintptr) unsafe.Pointer {
	return C.go_call_ptr_uptr6_func((*[0]byte)(fnc), C.uintptr_t(a1), C.uintptr_t(a2), C.uintptr_t(a3), C.uintptr_t(a4), C.uintptr_t(a5), C.uintptr_t(a6))
}

func CallPtrPtr(fnc unsafe.Pointer, a1 unsafe.Pointer) unsafe.Pointer {
	return C.go_call_ptr_ptr_func((*[0]byte)(fnc), a1)
}

func CallPtrPtr2(fnc unsafe.Pointer, a1 unsafe.Pointer, a2 unsafe.Pointer) unsafe.Pointer {
	return C.go_call_ptr_ptr2_func((*[0]byte)(fnc), a1, a2)
}

func CallPtrPtr3(fnc unsafe.Pointer, a1 unsafe.Pointer, a2 unsafe.Pointer, a3 unsafe.Pointer) unsafe.Pointer {
	return C.go_call_ptr_ptr3_func((*[0]byte)(fnc), a1, a2, a3)
}

func CallPtrPtr4(fnc unsafe.Pointer, a1 unsafe.Pointer, a2 unsafe.Pointer, a3 unsafe.Pointer, a4 unsafe.Pointer) unsafe.Pointer {
	return C.go_call_ptr_ptr4_func((*[0]byte)(fnc), a1, a2, a3, a4)
}

func CallPtrPtr5(fnc unsafe.Pointer, a1 unsafe.Pointer, a2 unsafe.Pointer, a3 unsafe.Pointer, a4 unsafe.Pointer, a5 unsafe.Pointer) unsafe.Pointer {
	return C.go_call_ptr_ptr5_func((*[0]byte)(fnc), a1, a2, a3, a4, a5)
}

func CallPtrPtr6(fnc unsafe.Pointer, a1 unsafe.Pointer, a2 unsafe.Pointer, a3 unsafe.Pointer, a4 unsafe.Pointer, a5 unsafe.Pointer, a6 unsafe.Pointer) unsafe.Pointer {
	return C.go_call_ptr_ptr6_func((*[0]byte)(fnc), a1, a2, a3, a4, a5, a6)
}

func CallPtrInt(fnc unsafe.Pointer, a1 int) unsafe.Pointer {
	return C.go_call_ptr_int_func((*[0]byte)(fnc), C.int(a1))
}

func CallPtrInt2(fnc unsafe.Pointer, a1 int, a2 int) unsafe.Pointer {
	return C.go_call_ptr_int2_func((*[0]byte)(fnc), C.int(a1), C.int(a2))
}

func CallPtrInt3(fnc unsafe.Pointer, a1 int, a2 int, a3 int) unsafe.Pointer {
	return C.go_call_ptr_int3_func((*[0]byte)(fnc), C.int(a1), C.int(a2), C.int(a3))
}

func CallPtrInt4(fnc unsafe.Pointer, a1 int, a2 int, a3 int, a4 int) unsafe.Pointer {
	return C.go_call_ptr_int4_func((*[0]byte)(fnc), C.int(a1), C.int(a2), C.int(a3), C.int(a4))
}

func CallPtrInt5(fnc unsafe.Pointer, a1 int, a2 int, a3 int, a4 int, a5 int) unsafe.Pointer {
	return C.go_call_ptr_int5_func((*[0]byte)(fnc), C.int(a1), C.int(a2), C.int(a3), C.int(a4), C.int(a5))
}

func CallPtrInt6(fnc unsafe.Pointer, a1 int, a2 int, a3 int, a4 int, a5 int, a6 int) unsafe.Pointer {
	return C.go_call_ptr_int6_func((*[0]byte)(fnc), C.int(a1), C.int(a2), C.int(a3), C.int(a4), C.int(a5), C.int(a6))
}

func CallIntVoid(fnc unsafe.Pointer) int {
	return int(C.go_call_int_void_func((*[0]byte)(fnc)))
}

func CallIntUPtr(fnc unsafe.Pointer, a1 uintptr) int {
	return int(C.go_call_int_uptr_func((*[0]byte)(fnc), C.uintptr_t(a1)))
}

func CallIntUPtr2(fnc unsafe.Pointer, a1 uintptr, a2 uintptr) int {
	return int(C.go_call_int_uptr2_func((*[0]byte)(fnc), C.uintptr_t(a1), C.uintptr_t(a2)))
}

func CallIntUPtr3(fnc unsafe.Pointer, a1 uintptr, a2 uintptr, a3 uintptr) int {
	return int(C.go_call_int_uptr3_func((*[0]byte)(fnc), C.uintptr_t(a1), C.uintptr_t(a2), C.uintptr_t(a3)))
}

func CallIntUPtr4(fnc unsafe.Pointer, a1 uintptr, a2 uintptr, a3 uintptr, a4 uintptr) int {
	return int(C.go_call_int_uptr4_func((*[0]byte)(fnc), C.uintptr_t(a1), C.uintptr_t(a2), C.uintptr_t(a3), C.uintptr_t(a4)))
}

func CallIntUPtr5(fnc unsafe.Pointer, a1 uintptr, a2 uintptr, a3 uintptr, a4 uintptr, a5 uintptr) int {
	return int(C.go_call_int_uptr5_func((*[0]byte)(fnc), C.uintptr_t(a1), C.uintptr_t(a2), C.uintptr_t(a3), C.uintptr_t(a4), C.uintptr_t(a5)))
}

func CallIntUPtr6(fnc unsafe.Pointer, a1 uintptr, a2 uintptr, a3 uintptr, a4 uintptr, a5 uintptr, a6 uintptr) int {
	return int(C.go_call_int_uptr6_func((*[0]byte)(fnc), C.uintptr_t(a1), C.uintptr_t(a2), C.uintptr_t(a3), C.uintptr_t(a4), C.uintptr_t(a5), C.uintptr_t(a6)))
}

func CallIntPtr(fnc unsafe.Pointer, a1 unsafe.Pointer) int {
	return int(C.go_call_int_ptr_func((*[0]byte)(fnc), a1))
}

func CallIntPtr2(fnc unsafe.Pointer, a1 unsafe.Pointer, a2 unsafe.Pointer) int {
	return int(C.go_call_int_ptr2_func((*[0]byte)(fnc), a1, a2))
}

func CallIntPtr3(fnc unsafe.Pointer, a1 unsafe.Pointer, a2 unsafe.Pointer, a3 unsafe.Pointer) int {
	return int(C.go_call_int_ptr3_func((*[0]byte)(fnc), a1, a2, a3))
}

func CallIntPtr4(fnc unsafe.Pointer, a1 unsafe.Pointer, a2 unsafe.Pointer, a3 unsafe.Pointer, a4 unsafe.Pointer) int {
	return int(C.go_call_int_ptr4_func((*[0]byte)(fnc), a1, a2, a3, a4))
}

func CallIntPtr5(fnc unsafe.Pointer, a1 unsafe.Pointer, a2 unsafe.Pointer, a3 unsafe.Pointer, a4 unsafe.Pointer, a5 unsafe.Pointer) int {
	return int(C.go_call_int_ptr5_func((*[0]byte)(fnc), a1, a2, a3, a4, a5))
}

func CallIntPtr6(fnc unsafe.Pointer, a1 unsafe.Pointer, a2 unsafe.Pointer, a3 unsafe.Pointer, a4 unsafe.Pointer, a5 unsafe.Pointer, a6 unsafe.Pointer) int {
	return int(C.go_call_int_ptr6_func((*[0]byte)(fnc), a1, a2, a3, a4, a5, a6))
}

func CallIntInt(fnc unsafe.Pointer, a1 int) int {
	return int(C.go_call_int_int_func((*[0]byte)(fnc), C.int(a1)))
}

func CallIntInt2(fnc unsafe.Pointer, a1 int, a2 int) int {
	return int(C.go_call_int_int2_func((*[0]byte)(fnc), C.int(a1), C.int(a2)))
}

func CallIntInt3(fnc unsafe.Pointer, a1 int, a2 int, a3 int) int {
	return int(C.go_call_int_int3_func((*[0]byte)(fnc), C.int(a1), C.int(a2), C.int(a3)))
}

func CallIntInt4(fnc unsafe.Pointer, a1 int, a2 int, a3 int, a4 int) int {
	return int(C.go_call_int_int4_func((*[0]byte)(fnc), C.int(a1), C.int(a2), C.int(a3), C.int(a4)))
}

func CallIntInt5(fnc unsafe.Pointer, a1 int, a2 int, a3 int, a4 int, a5 int) int {
	return int(C.go_call_int_int5_func((*[0]byte)(fnc), C.int(a1), C.int(a2), C.int(a3), C.int(a4), C.int(a5)))
}

func CallIntInt6(fnc unsafe.Pointer, a1 int, a2 int, a3 int, a4 int, a5 int, a6 int) int {
	return int(C.go_call_int_int6_func((*[0]byte)(fnc), C.int(a1), C.int(a2), C.int(a3), C.int(a4), C.int(a5), C.int(a6)))
}
