#ifndef NOX_PORT_CLIENT_DRAWABLE_UPDATE_CLOUD
#define NOX_PORT_CLIENT_DRAWABLE_UPDATE_CLOUD

#include "defs.h"

int sub_4CE200(int a1, int a2, int a3, int a4);

#endif // NOX_PORT_CLIENT_DRAWABLE_UPDATE_CLOUD
