#ifndef NOX_PORT_CLIENT_DRAWABLE_UPDATE_VORTEXUP
#define NOX_PORT_CLIENT_DRAWABLE_UPDATE_VORTEXUP

#include "defs.h"

int nox_xxx_updDrawVortexSource_4CC950(int a1, int a2);

#endif // NOX_PORT_CLIENT_DRAWABLE_UPDATE_VORTEXUP
