#ifndef NOX_PORT_CLIENT_DRAWABLE_UPDATE_HEALUP
#define NOX_PORT_CLIENT_DRAWABLE_UPDATE_HEALUP

#include "defs.h"

int sub_4CD450(uint32_t* a1, int a2);

#endif // NOX_PORT_CLIENT_DRAWABLE_UPDATE_HEALUP
