#ifndef NOX_PORT_CLIENT_DRAWABLE_UPDATE_MANABOMB
#define NOX_PORT_CLIENT_DRAWABLE_UPDATE_MANABOMB

#include "defs.h"

int nox_xxx_updDrawManabombCharge_4CCAC0(int a1, uint32_t* a2);

#endif // NOX_PORT_CLIENT_DRAWABLE_UPDATE_MANABOMB
