package legacy

import "github.com/noxworld-dev/opennox/v1/legacy/common/ccall"

var nox_parse_thing_draw_funcs = []nox_parse_thing_draw_funcs_t{
	{name: "NoDraw", draw: nil, kind: 0, parse_fnc: nil},
	{name: "DebugDraw", draw: ccall.FuncAddr(nox_thing_debug_draw), kind: 0, parse_fnc: nil},
	{name: "StaticDraw", draw: ccall.FuncAddr(nox_thing_static_draw), kind: 1, parse_fnc: nox_things_static_draw_parse},
	{name: "StaticRandomDraw", draw: ccall.FuncAddr(nox_thing_static_random_draw), kind: 2, parse_fnc: nox_things_static_random_draw_parse},
	{name: "DoorDraw", draw: ccall.FuncAddr(nox_thing_door_draw), kind: 2, parse_fnc: nox_things_door_draw_parse},
	{name: "AnimateDraw", draw: ccall.FuncAddr(nox_thing_animate_draw), kind: 3, parse_fnc: nox_things_animate_draw_parse},
	{name: "ConditionalAnimateDraw", draw: ccall.FuncAddr(nox_thing_cond_animate_draw), kind: 4, parse_fnc: nox_things_cond_animate_draw_parse},
	{name: "MonsterGeneratorDraw", draw: ccall.FuncAddr(nox_thing_monster_gen_draw), kind: 4, parse_fnc: nox_things_cond_animate_draw_parse},
	{name: "VectorAnimateDraw", draw: ccall.FuncAddr(nox_thing_vector_animate_draw), kind: 5, parse_fnc: nox_things_vector_animate_draw_parse},
	{name: "MonsterDraw", draw: ccall.FuncAddr(nox_thing_monster_draw), kind: 7, parse_fnc: nox_things_monster_draw_parse},
	{name: "MaidenDraw", draw: ccall.FuncAddr(nox_thing_maiden_draw), kind: 7, parse_fnc: nox_things_maiden_draw_parse},
	{name: "AnimateStateDraw", draw: ccall.FuncAddr(nox_thing_animate_state_draw), kind: 8, parse_fnc: nox_things_animate_state_draw_parse},
	{name: "PlayerDraw", draw: ccall.FuncAddr(nox_thing_player_draw), kind: 6, parse_fnc: nox_things_player_draw_parse},
	{name: "SlaveDraw", draw: ccall.FuncAddr(nox_thing_slave_draw), kind: 2, parse_fnc: nox_things_slave_draw_parse},
	{name: "TriggerDraw", draw: ccall.FuncAddr(nox_thing_trigger_draw), kind: 0, parse_fnc: nil},
	{name: "PressurePlateDraw", draw: ccall.FuncAddr(nox_thing_pressure_plate_draw), kind: 0, parse_fnc: nil},
	{name: "LightningDraw", draw: ccall.FuncAddr(nox_thing_lightning_draw), kind: 0, parse_fnc: nil},
	{name: "ChainLightningBoltDraw", draw: ccall.FuncAddr(nox_thing_chain_lightning_bolt_draw), kind: 0, parse_fnc: nil},
	{name: "EnergyBoltDraw", draw: ccall.FuncAddr(nox_thing_energy_bolt_draw), kind: 0, parse_fnc: nil},
	{name: "GreenBoltDraw", draw: ccall.FuncAddr(nox_thing_green_bolt_draw), kind: 0, parse_fnc: nil},
	{name: "PlasmaDraw", draw: ccall.FuncAddr(nox_thing_plasma_draw), kind: 0, parse_fnc: nil},
	{name: "YellowSparkDraw", draw: ccall.FuncAddr(nox_thing_yellow_spark_draw), kind: 0, parse_fnc: nil},
	{name: "RedSparkDraw", draw: ccall.FuncAddr(nox_thing_red_spark_draw), kind: 0, parse_fnc: nil},
	{name: "BlueSparkDraw", draw: ccall.FuncAddr(nox_thing_blue_spark_draw), kind: 0, parse_fnc: nil},
	{name: "CyanSparkDraw", draw: ccall.FuncAddr(nox_thing_cyan_spark_draw), kind: 0, parse_fnc: nil},
	{name: "GreenSparkDraw", draw: ccall.FuncAddr(nox_thing_green_spark_draw), kind: 0, parse_fnc: nil},
	{name: "VioletSparkDraw", draw: ccall.FuncAddr(nox_thing_violet_spark_draw), kind: 0, parse_fnc: nil},
	{name: "WhiteSparkDraw", draw: ccall.FuncAddr(nox_thing_white_spark_draw), kind: 0, parse_fnc: nil},
	{name: "BlueRainSparkDraw", draw: ccall.FuncAddr(nox_thing_blue_rain_spark_draw), kind: 0, parse_fnc: nil},
	{name: "DeathBallSparkDraw", draw: ccall.FuncAddr(nox_thing_death_ball_spark_draw), kind: 0, parse_fnc: nil},
	{name: "PixieDraw", draw: ccall.FuncAddr(nox_thing_pixie_draw), kind: 0, parse_fnc: nil},
	{name: "PixieDustDraw", draw: ccall.FuncAddr(nox_thing_pixie_dust_draw), kind: 0, parse_fnc: nil},
	{name: "ParticleDraw", draw: ccall.FuncAddr(nox_thing_particle_draw), kind: 0, parse_fnc: nil},
	{name: "BubbleDraw", draw: ccall.FuncAddr(nox_thing_bubble_draw), kind: 0, parse_fnc: nil},
	{name: "VortexDraw", draw: ccall.FuncAddr(nox_thing_vortex_draw), kind: 0, parse_fnc: nil},
	{name: "BlackPowderDraw", draw: ccall.FuncAddr(nox_thing_black_powder_draw), kind: 0, parse_fnc: nil},
	{name: "SpiderSpitDraw", draw: ccall.FuncAddr(nox_thing_spider_spit_draw), kind: 0, parse_fnc: nil},
	{name: "GlyphDraw", draw: ccall.FuncAddr(nox_thing_glyph_draw), kind: 3, parse_fnc: nox_things_animate_draw_parse},
	{name: "BoulderDraw", draw: ccall.FuncAddr(nox_thing_boulder_draw), kind: 2, parse_fnc: nox_things_slave_draw_parse},
	{name: "DrainManaDraw", draw: ccall.FuncAddr(nox_thing_drain_mana_draw), kind: 0, parse_fnc: nil},
	{name: "GlowOrbDraw", draw: ccall.FuncAddr(nox_thing_glow_orb_draw), kind: 0, parse_fnc: nil},
	{name: "GlowOrbMoveDraw", draw: ccall.FuncAddr(nox_thing_glow_orb_move_draw), kind: 0, parse_fnc: nil},
	{name: "MagicDraw", draw: ccall.FuncAddr(nox_thing_magic_draw), kind: 0, parse_fnc: nil},
	{name: "MagicMissileDraw", draw: ccall.FuncAddr(nox_thing_magic_missle_draw), kind: 0, parse_fnc: nil},
	{name: "MagicTailLinkDraw", draw: ccall.FuncAddr(nox_thing_magic_tail_link_draw), kind: 0, parse_fnc: nil},
	{name: "MagicMissileTailLinkDraw", draw: ccall.FuncAddr(nox_thing_magic_missle_tail_link_draw), kind: 0, parse_fnc: nil},
	{name: "MagicSparkleDraw", draw: ccall.FuncAddr(nox_thing_magic_sparkle_draw), kind: 0, parse_fnc: nil},
	{name: "PlayerWaypointDraw", draw: ccall.FuncAddr(nox_thing_player_waypoint_draw), kind: 0, parse_fnc: nil},
	{name: "WeaponDraw", draw: ccall.FuncAddr(nox_thing_weapon_draw), kind: 1, parse_fnc: nox_things_static_draw_parse},
	{name: "ArmorDraw", draw: ccall.FuncAddr(nox_thing_armor_draw), kind: 1, parse_fnc: nox_things_static_draw_parse},
	{name: "WeaponAnimateDraw", draw: ccall.FuncAddr(nox_thing_weapon_animate_draw), kind: 3, parse_fnc: nox_things_animate_draw_parse},
	{name: "ArmorAnimateDraw", draw: ccall.FuncAddr(nox_thing_armor_animate_draw), kind: 3, parse_fnc: nox_things_animate_draw_parse},
	{name: "FlagDraw", draw: ccall.FuncAddr(nox_thing_flag_draw), kind: 3, parse_fnc: nox_things_animate_draw_parse},
	{name: "BaseDraw", draw: ccall.FuncAddr(nox_thing_base_draw), kind: 1, parse_fnc: nox_things_static_draw_parse},
	{name: "NPCDraw", draw: ccall.FuncAddr(nox_thing_npc_draw), kind: 0, parse_fnc: nil},
	{name: "SphericalShieldDraw", draw: ccall.FuncAddr(nox_thing_spherical_shield_draw), kind: 3, parse_fnc: nox_things_animate_draw_parse},
	{name: "SummonEffectDraw", draw: ccall.FuncAddr(nox_thing_summon_effect_draw), kind: 3, parse_fnc: nox_things_animate_draw_parse},
	{name: "ReleasedSoulDraw", draw: ccall.FuncAddr(nox_thing_released_soul_draw), kind: 5, parse_fnc: nox_things_vector_animate_draw_parse},
	{name: "UndeadKillerDraw", draw: ccall.FuncAddr(nox_thing_undead_killer_draw), kind: 0, parse_fnc: nil},
	{name: "ArrowDraw", draw: ccall.FuncAddr(nox_thing_arrow_draw), kind: 2, parse_fnc: nox_things_slave_draw_parse},
	{name: "WeakArrowDraw", draw: ccall.FuncAddr(nox_thing_weak_arrow_draw), kind: 2, parse_fnc: nox_things_slave_draw_parse},
	{name: "ArrowTailLinkDraw", draw: ccall.FuncAddr(nox_thing_arrow_tail_link_draw), kind: 0, parse_fnc: nil},
	{name: "WeakArrowTailLinkDraw", draw: ccall.FuncAddr(nox_thing_weak_arrow_tail_link_draw), kind: 0, parse_fnc: nil},
	{name: "BlueRainDraw", draw: ccall.FuncAddr(nox_thing_blue_rain_draw), kind: 0, parse_fnc: nil},
	{name: "LevelUpDraw", draw: ccall.FuncAddr(nox_thing_levelup_draw), kind: 0, parse_fnc: nil},
	{name: "OblivionUpDraw", draw: ccall.FuncAddr(nox_thing_oblivion_up_draw), kind: 0, parse_fnc: nil},
	{name: "RainOrbDraw", draw: ccall.FuncAddr(nox_thing_rain_orb_draw), kind: 0, parse_fnc: nil},
	{name: "HarpoonDraw", draw: ccall.FuncAddr(nox_thing_harpoon_draw), kind: 2, parse_fnc: nox_things_slave_draw_parse},
	{name: "HarpoonRopeDraw", draw: ccall.FuncAddr(nox_thing_harpoon_rope_draw), kind: 0, parse_fnc: nil},
}
var nox_parse_thing_draw_funcs_cnt = int32(len(nox_parse_thing_draw_funcs))
