#ifndef NOX_PORT_CLIENT_DRAWABLE_UPDATE_CHARMUP
#define NOX_PORT_CLIENT_DRAWABLE_UPDATE_CHARMUP

#include "defs.h"

void  sub_4CD150(int a1, uint32_t* a2, int a3, int a4);

#endif // NOX_PORT_CLIENT_DRAWABLE_UPDATE_CHARMUP
