#ifndef NOX_PORT_CLIENT_DRAWABLE_UPDATE_MMISLUP
#define NOX_PORT_CLIENT_DRAWABLE_UPDATE_MMISLUP

#include "defs.h"

int nox_xxx_updDrawMagicMissile_4CD9E0(int a1, uint32_t* a2);

#endif // NOX_PORT_CLIENT_DRAWABLE_UPDATE_MMISLUP
