#ifndef NOX_PORT_CLIENT_DRAWABLE_UPDATE_SPARKLUP
#define NOX_PORT_CLIENT_DRAWABLE_UPDATE_SPARKLUP

#include "defs.h"

int __cdecl nox_xxx_updDrawSparkleTrail_4CDBF0(int a1, _DWORD* a2);

#endif // NOX_PORT_CLIENT_DRAWABLE_UPDATE_SPARKLUP
