#ifndef NOX_PORT_CLIENT_DRAWABLE_UPDATE_DRAINUP
#define NOX_PORT_CLIENT_DRAWABLE_UPDATE_DRAINUP

#include "defs.h"

int  sub_4CD690(uint32_t* a1, int a2);

#endif // NOX_PORT_CLIENT_DRAWABLE_UPDATE_DRAINUP
