#ifndef NOX_PORT_CLIENT_DRAWABLE_UPDATE_SPARKLUP
#define NOX_PORT_CLIENT_DRAWABLE_UPDATE_SPARKLUP

#include "defs.h"

int nox_xxx_updDrawSparkleTrail_4CDBF0(int a1, uint32_t* a2);

#endif // NOX_PORT_CLIENT_DRAWABLE_UPDATE_SPARKLUP
