#ifndef NOX_PORT_CLIENT_DRAWABLE_UPDATE_MTAILUP
#define NOX_PORT_CLIENT_DRAWABLE_UPDATE_MTAILUP

#include "defs.h"

void  nox_xxx_updDrawMagic_4CDD80(int a1, uint32_t* a2);

#endif // NOX_PORT_CLIENT_DRAWABLE_UPDATE_MTAILUP
