#ifndef NOX_PORT_CLIENT_DRAWABLE_UPDATE_FIREBALL
#define NOX_PORT_CLIENT_DRAWABLE_UPDATE_FIREBALL

#include "defs.h"

void  sub_4CCEA0(uint32_t* a1, int a2);

#endif // NOX_PORT_CLIENT_DRAWABLE_UPDATE_FIREBALL
