package blobdata

import (
	"unsafe"
)

type Ptrs struct {
	Ptr_nox_xxx_aClosewoodengat_587000_133480 *unsafe.Pointer
	Ptr_dword_587000_155144                   *unsafe.Pointer
	Ptr_dword_587000_127004                   *unsafe.Pointer
	Ptr_dword_587000_93164                    *unsafe.Pointer
	Ptr_dword_587000_122852                   *unsafe.Pointer
	Ptr_dword_587000_81128                    *unsafe.Pointer

	Ptr_nox_xxx_parseWeapColor_411C40           unsafe.Pointer
	Ptr_sub_411D90                              unsafe.Pointer
	Ptr_sub_40E4F0                              unsafe.Pointer
	Ptr_sub_40E490                              unsafe.Pointer
	Ptr_sub_40E4B0                              unsafe.Pointer
	Ptr_sub_40C960                              unsafe.Pointer
	Ptr_sub_40C140                              unsafe.Pointer
	Ptr_sub_40C1B0                              unsafe.Pointer
	Ptr_sub_40CA60                              unsafe.Pointer
	Ptr_sub_40C1F0                              unsafe.Pointer
	Ptr_nox_xxx_somejoinproc_40CD60             unsafe.Pointer
	Ptr_sub_40C240                              unsafe.Pointer
	Ptr_sub_40C2E0                              unsafe.Pointer
	Ptr_sub_40C420                              unsafe.Pointer
	Ptr_sub_40C4E0                              unsafe.Pointer
	Ptr_sub_40C530                              unsafe.Pointer
	Ptr_sub_40C580                              unsafe.Pointer
	Ptr_sub_40CDC0                              unsafe.Pointer
	Ptr_sub_40C5C0                              unsafe.Pointer
	Ptr_sub_40C600                              unsafe.Pointer
	Ptr_sub_40CBA0                              unsafe.Pointer
	Ptr_sub_40CBE0                              unsafe.Pointer
	Ptr_sub_40C9D0                              unsafe.Pointer
	Ptr_sub_40C650                              unsafe.Pointer
	Ptr_sub_40C660                              unsafe.Pointer
	Ptr_sub_40C670                              unsafe.Pointer
	Ptr_sub_40C690                              unsafe.Pointer
	Ptr_sub_40C710                              unsafe.Pointer
	Ptr_sub_40C720                              unsafe.Pointer
	Ptr_sub_40C7A0                              unsafe.Pointer
	Ptr_sub_40C7D0                              unsafe.Pointer
	Ptr_sub_40C830                              unsafe.Pointer
	Ptr_sub_40C880                              unsafe.Pointer
	Ptr_sub_40C8C0                              unsafe.Pointer
	Ptr_sub_40C8F0                              unsafe.Pointer
	Ptr_sub_40C4F0                              unsafe.Pointer
	Ptr_sub_40C510                              unsafe.Pointer
	Ptr_sub_40C500                              unsafe.Pointer
	Ptr_sub_40C520                              unsafe.Pointer
	Ptr_sub_40CA40                              unsafe.Pointer
	Ptr_sub_40CD50                              unsafe.Pointer
	Ptr_sub_40CB90                              unsafe.Pointer
	Ptr_sub_40CA50                              unsafe.Pointer
	Ptr_sub_40E6C0                              unsafe.Pointer
	Ptr_sub_40E680                              unsafe.Pointer
	Ptr_sub_40DBB0                              unsafe.Pointer
	Ptr_sub_40DBE0                              unsafe.Pointer
	Ptr_sub_40DC10                              unsafe.Pointer
	Ptr_sub_40DC60                              unsafe.Pointer
	Ptr_sub_40DC50                              unsafe.Pointer
	Ptr_sub_40E890                              unsafe.Pointer
	Ptr_sub_40E850                              unsafe.Pointer
	Ptr_sub_40DD00                              unsafe.Pointer
	Ptr_sub_40DD10                              unsafe.Pointer
	Ptr_sub_40DD60                              unsafe.Pointer
	Ptr_sub_40DD70                              unsafe.Pointer
	Ptr_sub_40DE10                              unsafe.Pointer
	Ptr_sub_40DE90                              unsafe.Pointer
	Ptr_nox_xxx_unknown_libname_86_57F634       unsafe.Pointer
	Ptr_sub_4DFB50                              unsafe.Pointer
	Ptr_nox_xxx_effectSpeedEngage_4DFC30        unsafe.Pointer
	Ptr_sub_4DFD10                              unsafe.Pointer
	Ptr_nox_xxx_buff_4DFD80                     unsafe.Pointer
	Ptr_nox_xxx_checkPoisonProtectEnch_4DFDE0   unsafe.Pointer
	Ptr_sub_4E0140                              unsafe.Pointer
	Ptr_nox_xxx_parseWeapDescription_411B90     unsafe.Pointer
	Ptr_sub_411E60                              unsafe.Pointer
	Ptr_sub_411ED0                              unsafe.Pointer
	Ptr_sub_411F20                              unsafe.Pointer
	Ptr_sub_411F70                              unsafe.Pointer
	Ptr_sub_411FC0                              unsafe.Pointer
	Ptr_nox_xxx_parseWeapDamageType_412010      unsafe.Pointer
	Ptr_sub_412060                              unsafe.Pointer
	Ptr_sub_4120B0                              unsafe.Pointer
	Ptr_sub_41A590                              unsafe.Pointer
	Ptr_sub_41AA30                              unsafe.Pointer
	Ptr_sub_41AC30                              unsafe.Pointer
	Ptr_nox_xxx_guiFieldbook_41B420             unsafe.Pointer
	Ptr_nox_xxx_guiSpellbook_41B660             unsafe.Pointer
	Ptr_nox_xxx_guiEnchantment_41B9C0           unsafe.Pointer
	Ptr_sub_41BEC0                              unsafe.Pointer
	Ptr_sub_41C080                              unsafe.Pointer
	Ptr_sub_41C200                              unsafe.Pointer
	Ptr_sub_41C280                              unsafe.Pointer
	Ptr_nox_xxx_parseFileInfoData_41C3B0        unsafe.Pointer
	Ptr_sub_41C780                              unsafe.Pointer
	Ptr_sub_41DB90                              unsafe.Pointer
	Ptr_sub_41E080                              unsafe.Pointer
	Ptr_sub_41DD40                              unsafe.Pointer
	Ptr_sub_41DD10                              unsafe.Pointer
	Ptr_sub_41DDB0                              unsafe.Pointer
	Ptr_sub_41DFC0                              unsafe.Pointer
	Ptr_sub_41E0D0                              unsafe.Pointer
	Ptr_sub_41E170                              unsafe.Pointer
	Ptr_sub_41E1B0                              unsafe.Pointer
	Ptr_sub_468060                              unsafe.Pointer
	Ptr_sub_467F30                              unsafe.Pointer
	Ptr_sub_44AF70                              unsafe.Pointer
	Ptr_sub_446A90                              unsafe.Pointer
	Ptr_sub_468DC0                              unsafe.Pointer
	Ptr_sub_4683B0                              unsafe.Pointer
	Ptr_sub_43EC30                              unsafe.Pointer
	Ptr_sub_43ECB0                              unsafe.Pointer
	Ptr_sub_43ED00                              unsafe.Pointer
	Ptr_sub_43EFD0                              unsafe.Pointer
	Ptr_sub_43F010                              unsafe.Pointer
	Ptr_sub_43F030                              unsafe.Pointer
	Ptr_sub_43F050                              unsafe.Pointer
	Ptr_sub_43F060                              unsafe.Pointer
	Ptr_sub_43F0D0                              unsafe.Pointer
	Ptr_sub_43E940                              unsafe.Pointer
	Ptr_sub_43E9F0                              unsafe.Pointer
	Ptr_sub_43EA20                              unsafe.Pointer
	Ptr_sub_43EC10                              unsafe.Pointer
	Ptr_sub_446AE0_wol_chat                     unsafe.Pointer
	Ptr_sub_4A7A80                              unsafe.Pointer
	Ptr_sub_4A7AC0                              unsafe.Pointer
	Ptr_sub_4A7B00                              unsafe.Pointer
	Ptr_sub_4A7B40                              unsafe.Pointer
	Ptr_sub_4A7BA0                              unsafe.Pointer
	Ptr_sub_4A7BC0                              unsafe.Pointer
	Ptr_sub_4A7C00                              unsafe.Pointer
	Ptr_sub_4A7C40                              unsafe.Pointer
	Ptr_sub_4A7C60                              unsafe.Pointer
	Ptr_sub_4A7CE0                              unsafe.Pointer
	Ptr_sub_4A7D00                              unsafe.Pointer
	Ptr_sub_4A7D50                              unsafe.Pointer
	Ptr_nox_xxx_updDrawColorlight_4CE390        unsafe.Pointer
	Ptr_nox_xxx_updDrawCloud_4CE1D0             unsafe.Pointer
	Ptr_sub_4CE360                              unsafe.Pointer
	Ptr_nox_xxx_updDrawDBall_4CDF80             unsafe.Pointer
	Ptr_sub_4CE0A0                              unsafe.Pointer
	Ptr_nox_xxx_updDrawDBallCharge_4CE0C0       unsafe.Pointer
	Ptr_nox_xxx_updDrawMagic_4CDD80             unsafe.Pointer
	Ptr_nox_xxx_updDrawSparkleTrail_4CDBF0      unsafe.Pointer
	Ptr_nox_xxx_updDrawMagicMissile_4CD9E0      unsafe.Pointer
	Ptr_nox_xxx_updDrawTeleportWake_4CD8D0      unsafe.Pointer
	Ptr_sub_4CD690                              unsafe.Pointer
	Ptr_sub_4CD450                              unsafe.Pointer
	Ptr_sub_4CD400                              unsafe.Pointer
	Ptr_sub_4CCE70                              unsafe.Pointer
	Ptr_sub_4CD090                              unsafe.Pointer
	Ptr_sub_4CD0C0                              unsafe.Pointer
	Ptr_sub_4CD0F0                              unsafe.Pointer
	Ptr_sub_4CD120                              unsafe.Pointer
	Ptr_nox_xxx_updDrawFist_4CCDB0              unsafe.Pointer
	Ptr_sub_4CCD00                              unsafe.Pointer
	Ptr_nox_xxx_updDrawUndeadKiller_4CCCF0      unsafe.Pointer
	Ptr_nox_xxx_updDrawManabombCharge_4CCAC0    unsafe.Pointer
	Ptr_nox_xxx_updDrawVortexSource_4CC950      unsafe.Pointer
	Ptr_sub_4CA650                              unsafe.Pointer
	Ptr_nox_xxx_updDrawMonsterGen_4BC920        unsafe.Pointer
	Ptr_sub_454120                              unsafe.Pointer
	Ptr_sub_453750                              unsafe.Pointer
	Ptr_nox_xxx_monsterIdleStarted_546820       unsafe.Pointer
	Ptr_nox_xxx_monsterUpdateIdleLogic_546850   unsafe.Pointer
	Ptr_nox_xxx_mobActionWait_544960            unsafe.Pointer
	Ptr_sub_532100                              unsafe.Pointer
	Ptr_nox_xxx_mobActionWaitRelative_544990    unsafe.Pointer
	Ptr_nox_xxx_mobActionEscort_546430          unsafe.Pointer
	Ptr_sub_546410                              unsafe.Pointer
	Ptr_sub_546420                              unsafe.Pointer
	Ptr_nox_xxx_mobActionGuard_546010           unsafe.Pointer
	Ptr_nox_xxx_mobActionHunt_5449D0            unsafe.Pointer
	Ptr_nox_xxx_mobActionRetreat_545440         unsafe.Pointer
	Ptr_nox_xxx_mobActionMoveTo_5443F0          unsafe.Pointer
	Ptr_nox_xxx_mobActionMoveToFar_5445C0       unsafe.Pointer
	Ptr_nox_xxx_mobActionDodge_544640           unsafe.Pointer
	Ptr_sub_545790                              unsafe.Pointer
	Ptr_nox_xxx_mobActionRoam_5457E0            unsafe.Pointer
	Ptr_sub_5457C0                              unsafe.Pointer
	Ptr_nox_xxx_mobActionPickupObject_544B90    unsafe.Pointer
	Ptr_nullsub_66                              unsafe.Pointer
	Ptr_nullsub_67                              unsafe.Pointer
	Ptr_sub_5456B0                              unsafe.Pointer
	Ptr_sub_5456D0                              unsafe.Pointer
	Ptr_sub_5456C0                              unsafe.Pointer
	Ptr_nox_xxx_mobActionFightStart_531E20      unsafe.Pointer
	Ptr_nox_xxx_mobActionFight_531EC0           unsafe.Pointer
	Ptr_sub_531E90                              unsafe.Pointer
	Ptr_nox_xxx_mobActionMelee1_532130          unsafe.Pointer
	Ptr_nox_xxx_mobActionMeleeAtt_532440        unsafe.Pointer
	Ptr_sub_532540                              unsafe.Pointer
	Ptr_nox_xxx_mobActionMissileAtt_532610      unsafe.Pointer
	Ptr_nox_xxx_mobActionCastOnObj_541360       unsafe.Pointer
	Ptr_nox_xxx_mobActionCastOnPoint_541560     unsafe.Pointer
	Ptr_nox_xxx_mobActionCastStart_5415F0       unsafe.Pointer
	Ptr_nox_xxx_mobActionCastStopMB_541590      unsafe.Pointer
	Ptr_nox_xxx_mobActionCastFinishMB_5415C0    unsafe.Pointer
	Ptr_nox_xxx_monsterShieldBlockStart_532070  unsafe.Pointer
	Ptr_nox_xxx_monsterShieldBlockStop_5320E0   unsafe.Pointer
	Ptr_sub_532110                              unsafe.Pointer
	Ptr_sub_544740                              unsafe.Pointer
	Ptr_nox_xxx_mobActionFlee_544760            unsafe.Pointer
	Ptr_sub_544750                              unsafe.Pointer
	Ptr_sub_545210                              unsafe.Pointer
	Ptr_sub_545300                              unsafe.Pointer
	Ptr_sub_545340                              unsafe.Pointer
	Ptr_sub_5453E0                              unsafe.Pointer
	Ptr_nox_xxx_mobActionRandomWalk_545020      unsafe.Pointer
	Ptr_nox_xxx_mobGenericDeath_544C40          unsafe.Pointer
	Ptr_sub_544D60                              unsafe.Pointer
	Ptr_nox_xxx_zombieBurnDeleteCheck_544CA0    unsafe.Pointer
	Ptr_nox_xxx_mobActionDead1_544D80           unsafe.Pointer
	Ptr_nox_xxx_mobActionDead2_544EC0           unsafe.Pointer
	Ptr_nox_xxx_mobActionReportComplete_544FF0  unsafe.Pointer
	Ptr_nox_xxx_mobActionMorphToChest_5348D0    unsafe.Pointer
	Ptr_nox_xxx_mobActionMorphBackToSelf_534910 unsafe.Pointer
	Ptr_nox_xxx_mobActionGetUp_534A90           unsafe.Pointer
	Ptr_nox_xxx_mobActionConfuse_545140         unsafe.Pointer
	Ptr_nox_xxx_mobActionReturnToHome_544920    unsafe.Pointer
	Ptr_sub_544950                              unsafe.Pointer
	Ptr_sub_544930                              unsafe.Pointer
	Ptr_sub_544940                              unsafe.Pointer
	Ptr_nox_xxx_strikeOgre_549220               unsafe.Pointer
	Ptr_nox_xxx_strikeScorpion_5495B0           unsafe.Pointer
	Ptr_nox_xxx_strikeVileZombie_549700         unsafe.Pointer
	Ptr_nox_xxx_strikeStoneGolem_5497E0         unsafe.Pointer
	Ptr_nox_xxx_strikeMechGolem_549960          unsafe.Pointer
	Ptr_nox_xxx_strikeWasp_549980               unsafe.Pointer
	Ptr_nox_xxx_strikeSpider_549BC0             unsafe.Pointer
	Ptr_nox_xxx_strikeSpittingSpider_549CA0     unsafe.Pointer
	Ptr_nox_xxx_strikeGhost_549A60              unsafe.Pointer
	Ptr_nox_xxx_strikeBomber_549BB0             unsafe.Pointer
	Ptr_nox_xxx_strikeMonsterDefault_549380     unsafe.Pointer
	Ptr_sub_549D80                              unsafe.Pointer
	Ptr_sub_549E00                              unsafe.Pointer
	Ptr_sub_549E70                              unsafe.Pointer
	Ptr_sub_549E90                              unsafe.Pointer
	Ptr_sub_549FA0                              unsafe.Pointer
	Ptr_sub_54A150                              unsafe.Pointer
	Ptr_sub_54A250                              unsafe.Pointer
	Ptr_sub_54A310                              unsafe.Pointer
	Ptr_sub_54A750                              unsafe.Pointer
	Ptr_nox_xxx_monsterDeadTroll_54A270         unsafe.Pointer
	Ptr_sub_54A890                              unsafe.Pointer
	Ptr_sub_54A900                              unsafe.Pointer
	Ptr_sub_54A7D0                              unsafe.Pointer
	Ptr_sub_54A850                              unsafe.Pointer
	Ptr_sub_54A950                              unsafe.Pointer
}
